/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelOpcInformes.java
 *
 * Created on 25/09/2012, 22:23:18
 */
package gui;

import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author emmmau
 */
public class PanelOpcInformes extends javax.swing.JPanel {
   static PanelOpcInformes unicaInstancia;
    private DefaultTableModel modeloTabla;
    private ButtonGroup grupoElijeCampania;
    private int idCampaniaElegida;
    private int NRO_COL_ID_CAMP;
    private int NRO_COL_ELEGIR;
    private int NRO_COL_FECHA_INI;
    private int NRO_COL_FECHA_FIN;
    private int NRO_COL_BARCO;
    private int NRO_COL_CAJONES;
    private int NRO_COL_CAPITAN;
    private int NRO_COL_NOMBRE_CAMP;
    private int cantColumnas;

    /** Creates new form PanelOpcInformes */
    public PanelOpcInformes() {
        initComponents();
        inicializador();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new org.jdesktop.swingx.JXPanel();
        lblTituloInformes = new org.jdesktop.swingx.JXLabel();
        panelMedio = new org.jdesktop.swingx.JXPanel();
        panelTablaCampanias = new org.jdesktop.swingx.JXPanel();
        panelTituloTabla = new org.jdesktop.swingx.JXPanel();
        lblTituloTabla = new org.jdesktop.swingx.JXLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCampanias = new org.jdesktop.swingx.JXTable();
        panelSeleccionDatos = new org.jdesktop.swingx.JXPanel();
        panelTituloSeleccion = new org.jdesktop.swingx.JXPanel();
        lblTituloSeleccion = new org.jdesktop.swingx.JXLabel();
        panelCampos = new org.jdesktop.swingx.JXPanel();
        chkCajonesPorEspecie = new javax.swing.JCheckBox();
        chkLances = new javax.swing.JCheckBox();
        chkAlertasOcurridas = new javax.swing.JCheckBox();
        panelInferior = new org.jdesktop.swingx.JXPanel();
        btnGeneraInforme = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.BorderLayout());

        panelSuperior.setMaximumSize(new java.awt.Dimension(500, 30));
        panelSuperior.setMinimumSize(new java.awt.Dimension(500, 30));
        panelSuperior.setPreferredSize(new java.awt.Dimension(500, 30));

        lblTituloInformes.setText("Informes");
        lblTituloInformes.setFont(new java.awt.Font("Arial", 0, 18));
        panelSuperior.add(lblTituloInformes);

        add(panelSuperior, java.awt.BorderLayout.NORTH);

        panelMedio.setMaximumSize(new java.awt.Dimension(500, 420));
        panelMedio.setMinimumSize(new java.awt.Dimension(500, 420));

        panelTablaCampanias.setMaximumSize(new java.awt.Dimension(450, 180));
        panelTablaCampanias.setMinimumSize(new java.awt.Dimension(450, 180));
        panelTablaCampanias.setPreferredSize(new java.awt.Dimension(450, 180));

        panelTituloTabla.setMaximumSize(new java.awt.Dimension(450, 30));
        panelTituloTabla.setMinimumSize(new java.awt.Dimension(450, 30));
        panelTituloTabla.setPreferredSize(new java.awt.Dimension(450, 30));
        panelTituloTabla.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTituloTabla.setText("Elija la campaña de la cual desea generar el informe:");
        lblTituloTabla.setFont(new java.awt.Font("Tahoma", 0, 14));
        panelTituloTabla.add(lblTituloTabla);

        panelTablaCampanias.add(panelTituloTabla);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(450, 220));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(450, 220));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 135));

        tablaCampanias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Elegir", "Fechas", "Campaña", "Resumen", "Barco", "Capitan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCampanias.setShowGrid(true);
        jScrollPane1.setViewportView(tablaCampanias);
        tablaCampanias.getColumnModel().getColumn(0).setMinWidth(30);
        tablaCampanias.getColumnModel().getColumn(0).setPreferredWidth(30);

        panelTablaCampanias.add(jScrollPane1);

        panelMedio.add(panelTablaCampanias);

        panelSeleccionDatos.setMaximumSize(new java.awt.Dimension(500, 240));
        panelSeleccionDatos.setMinimumSize(new java.awt.Dimension(500, 240));
        panelSeleccionDatos.setPreferredSize(new java.awt.Dimension(500, 240));
        panelSeleccionDatos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        panelTituloSeleccion.setMaximumSize(new java.awt.Dimension(500, 30));
        panelTituloSeleccion.setMinimumSize(new java.awt.Dimension(500, 30));
        panelTituloSeleccion.setPreferredSize(new java.awt.Dimension(500, 30));
        panelTituloSeleccion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        lblTituloSeleccion.setText("Datos de la campaña a incluir en el informe:");
        lblTituloSeleccion.setFont(new java.awt.Font("Tahoma", 0, 14));
        panelTituloSeleccion.add(lblTituloSeleccion);

        panelSeleccionDatos.add(panelTituloSeleccion);

        panelCampos.setMaximumSize(new java.awt.Dimension(500, 210));
        panelCampos.setMinimumSize(new java.awt.Dimension(500, 210));
        panelCampos.setPreferredSize(new java.awt.Dimension(500, 210));
        panelCampos.setLayout(new java.awt.GridLayout(5, 2));

        chkCajonesPorEspecie.setFont(new java.awt.Font("Tahoma", 0, 12));
        chkCajonesPorEspecie.setText("Cajones por especie");
        panelCampos.add(chkCajonesPorEspecie);

        chkLances.setFont(new java.awt.Font("Tahoma", 0, 12));
        chkLances.setText("Lances");
        panelCampos.add(chkLances);

        chkAlertasOcurridas.setFont(new java.awt.Font("Tahoma", 0, 12));
        chkAlertasOcurridas.setText("Alertas ocurridas");
        chkAlertasOcurridas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAlertasOcurridasActionPerformed(evt);
            }
        });
        panelCampos.add(chkAlertasOcurridas);

        panelSeleccionDatos.add(panelCampos);

        panelMedio.add(panelSeleccionDatos);

        add(panelMedio, java.awt.BorderLayout.CENTER);

        panelInferior.setMaximumSize(new java.awt.Dimension(500, 50));
        panelInferior.setMinimumSize(new java.awt.Dimension(500, 50));
        panelInferior.setPreferredSize(new java.awt.Dimension(500, 50));
        panelInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        btnGeneraInforme.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnGeneraInforme.setText("Generar Informe");
        btnGeneraInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneraInformeActionPerformed(evt);
            }
        });
        panelInferior.add(btnGeneraInforme);

        add(panelInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

private void chkAlertasOcurridasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAlertasOcurridasActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_chkAlertasOcurridasActionPerformed

private void btnGeneraInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneraInformeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btnGeneraInformeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneraInforme;
    private javax.swing.JCheckBox chkAlertasOcurridas;
    private javax.swing.JCheckBox chkCajonesPorEspecie;
    private javax.swing.JCheckBox chkLances;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel lblTituloInformes;
    private org.jdesktop.swingx.JXLabel lblTituloSeleccion;
    private org.jdesktop.swingx.JXLabel lblTituloTabla;
    private org.jdesktop.swingx.JXPanel panelCampos;
    private org.jdesktop.swingx.JXPanel panelInferior;
    private org.jdesktop.swingx.JXPanel panelMedio;
    private org.jdesktop.swingx.JXPanel panelSeleccionDatos;
    private org.jdesktop.swingx.JXPanel panelSuperior;
    private org.jdesktop.swingx.JXPanel panelTablaCampanias;
    private org.jdesktop.swingx.JXPanel panelTituloSeleccion;
    private org.jdesktop.swingx.JXPanel panelTituloTabla;
    private org.jdesktop.swingx.JXTable tablaCampanias;
    // End of variables declaration//GEN-END:variables
   
    public static PanelOpcInformes getInstance() {
       if (unicaInstancia == null) {
          unicaInstancia = new PanelOpcInformes();          
       }
       return unicaInstancia;
    }

     private void inicializador() {
        NRO_COL_ID_CAMP=0;
        NRO_COL_ELEGIR=1;
        NRO_COL_FECHA_INI=2;
        NRO_COL_FECHA_FIN=3;
        NRO_COL_CAJONES=4;
        NRO_COL_BARCO=5;
        NRO_COL_CAPITAN=6;
        NRO_COL_NOMBRE_CAMP=7;
        cantColumnas=8;
        modeloTabla = (DefaultTableModel) tablaCampanias.getModel();
        tablaCampanias.setModel(modeloTabla);
        //seteo los radiobotones de la tabla
        grupoElijeCampania = new ButtonGroup();
        tablaCampanias.getColumn(1).setCellRenderer(new RadioButtonRenderer());
        tablaCampanias.getColumn(1).setCellEditor(new RadioButtonEditor(new JCheckBox()));
    }

     public void agregaUnaFilaCampania(int id, String nombre, String barco, String capitan,
        int estado, Date fechaInicio, Date fechaFin, int cantCajones) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Object[] fila = new Object[cantColumnas]; //creamos la fila
        if (fechaInicio != null) { fila[NRO_COL_FECHA_INI]=sdf.format(fechaInicio); }
        if (fechaFin != null){ fila[NRO_COL_FECHA_FIN]=sdf.format(fechaFin); }
        fila[NRO_COL_CAPITAN]=capitan;
        fila[NRO_COL_NOMBRE_CAMP]=nombre;
        fila[NRO_COL_BARCO]=barco;
        fila[NRO_COL_ID_CAMP]=id;
        fila[NRO_COL_CAJONES]=cantCajones;
        JRadioButton radioBtnCampania = new JRadioButton();
        grupoElijeCampania.add(radioBtnCampania);//lo agrego al grupo, lo cual me garantiza la selección simple
        fila[NRO_COL_ELEGIR]= radioBtnCampania;

        modeloTabla.addRow(fila);
    }

      public void vaciaTabla() {
        modeloTabla.setRowCount(0);
        setIdCampaniaElegida(-1);
    }

      public void setIdCampaniaElegida(int idCampaniaElegida) {
        if (idCampaniaElegida>=0){
            this.idCampaniaElegida = Integer.parseInt(modeloTabla.getValueAt(idCampaniaElegida, 0).toString());
        }
        else
          { this.idCampaniaElegida = idCampaniaElegida;
          }
   }

      public void habilitaPanelTablaCampanias(boolean estado){
        tablaCampanias.setEnabled(estado);
  }

      class RadioButtonRenderer implements TableCellRenderer {
        public Component getTableCellRendererComponent(JTable table, Object value,
                       boolean isSelected, boolean hasFocus, int row, int column) {
        if (value==null) return null;
        return (Component)value;
  }
}
      class RadioButtonEditor extends DefaultCellEditor implements ItemListener {
        private JRadioButton button;
        public RadioButtonEditor(JCheckBox checkBox) {
        super(checkBox);
  }
      public Component getTableCellEditorComponent(JTable table,Object value,boolean isSelected,int row,int column) {
        if (value==null) return null;
        button = (JRadioButton)value;
        button.addItemListener(this);
        PanelOpcInformes.getInstance().setIdCampaniaElegida(row);
        return (Component)value;
  }
      public Object getCellEditorValue() {
        button.removeItemListener(this);
        return button;
  }
      public void itemStateChanged(ItemEvent e) {
        super.fireEditingStopped();
  }
}

}