/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelOpcAlertasAgregaEdita.java
 *
 * Created on 15/04/2012, 01:29:40
 */
package gui;

import controllers.ControllerAlertas;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.alertas.AdministraAlertas;
import modelo.alertas.Alerta;
import modelo.alertas.Condicion;
import modelo.alertas.Relacion;
import modelo.alertas.Variable;

/**
 *
 * @author Sebastian
 */
public class PanelOpcAlertasAgregaEdita extends javax.swing.JPanel {
    
    static PanelOpcAlertasAgregaEdita unicaInstancia;


    private int NRO_COL_ID_CONDICION;
    private int NRO_COL_DESCRIPCION;
    private int NRO_COL_ACCIONES;
    private int cantColumnas;
    private boolean modificandoCondicion;
    private boolean guardandoCondicion;
    private Color colorOriginalBtnIniciar;
    private DefaultTableModel modeloTabla;
    private Alerta alertaAct;
    private ArrayList <modelo.alertas.Variable> variables;
    private ArrayList <modelo.alertas.Relacion> relaciones;
    private boolean configCombo1=false;
    private boolean configCombo2=false;
    private boolean varRelCargadas=false;
    private int idProvCondicion;
    
    

    /** Creates new form PanelOpcAlertasAgregaEdita */
    private PanelOpcAlertasAgregaEdita() {
        initComponents();
        inicializador();
        cargaIconosDeBotones();    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregaEdita = new org.jdesktop.swingx.JXPanel();
        panelSuperior = new org.jdesktop.swingx.JXPanel();
        lblAlertaNueva = new org.jdesktop.swingx.JXLabel();
        scrollPanelMedio = new javax.swing.JScrollPane();
        panelMedio = new org.jdesktop.swingx.JXPanel();
        panelDatosAlerta = new org.jdesktop.swingx.JXPanel();
        panelNombre = new org.jdesktop.swingx.JXPanel();
        panelLblNombre = new org.jdesktop.swingx.JXPanel();
        lblNombre = new org.jdesktop.swingx.JXLabel();
        panelCampoNombre = new org.jdesktop.swingx.JXPanel();
        campoNombre = new javax.swing.JTextField();
        panelEstado = new org.jdesktop.swingx.JXPanel();
        panelLblEstado = new org.jdesktop.swingx.JXPanel();
        lblEstado = new org.jdesktop.swingx.JXLabel();
        panelComboEstado = new org.jdesktop.swingx.JXPanel();
        comboEstado = new javax.swing.JComboBox();
        panelTxtCondiciones = new org.jdesktop.swingx.JXPanel();
        lblCondiciones = new org.jdesktop.swingx.JXLabel();
        panelTablaCondiciones = new org.jdesktop.swingx.JXPanel();
        scrollTablaCondiciones = new javax.swing.JScrollPane();
        tablaCondiciones = new org.jdesktop.swingx.JXTable();
        panelAccionesCondicion = new org.jdesktop.swingx.JXPanel();
        lblAccionesCondicion = new org.jdesktop.swingx.JXLabel();
        panelAcciones = new org.jdesktop.swingx.JXPanel();
        btnModificar = new org.jdesktop.swingx.JXHyperlink();
        btnEliminar = new org.jdesktop.swingx.JXHyperlink();
        btnInsertar = new org.jdesktop.swingx.JXHyperlink();
        panelRelleno = new org.jdesktop.swingx.JXPanel();
        jLabel1 = new javax.swing.JLabel();
        panelNuevaCondicion = new org.jdesktop.swingx.JXPanel();
        panelDatosCondicion = new org.jdesktop.swingx.JXPanel();
        panelVariable = new org.jdesktop.swingx.JXPanel();
        panelLblVariable = new org.jdesktop.swingx.JXPanel();
        lblVariable = new org.jdesktop.swingx.JXLabel();
        panelComboVariable = new org.jdesktop.swingx.JXPanel();
        jComboBox1 = new javax.swing.JComboBox();
        panelRelacion = new org.jdesktop.swingx.JXPanel();
        panelLblRelacion = new org.jdesktop.swingx.JXPanel();
        lblRelacion = new org.jdesktop.swingx.JXLabel();
        panelComboRelacion = new org.jdesktop.swingx.JXPanel();
        jComboBox2 = new javax.swing.JComboBox();
        panelValMin = new org.jdesktop.swingx.JXPanel();
        panelLblValMin = new org.jdesktop.swingx.JXPanel();
        lblValMin = new org.jdesktop.swingx.JXLabel();
        panelCampoValMin = new org.jdesktop.swingx.JXPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelValMax = new org.jdesktop.swingx.JXPanel();
        panelLblValMax = new org.jdesktop.swingx.JXPanel();
        lblValMax = new org.jdesktop.swingx.JXLabel();
        panelCampoValMax = new org.jdesktop.swingx.JXPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelBtnAgrega = new org.jdesktop.swingx.JXPanel();
        btnAgregar = new javax.swing.JButton();
        panelInferior = new org.jdesktop.swingx.JXPanel();
        btnVolver = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(500, 600));
        setMinimumSize(new java.awt.Dimension(500, 600));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.BorderLayout());

        panelAgregaEdita.setPreferredSize(new java.awt.Dimension(500, 600));
        panelAgregaEdita.setLayout(new java.awt.BorderLayout());

        panelSuperior.setMaximumSize(new java.awt.Dimension(500, 30));
        panelSuperior.setMinimumSize(new java.awt.Dimension(500, 30));
        panelSuperior.setPreferredSize(new java.awt.Dimension(500, 30));

        lblAlertaNueva.setText("Alerta Nueva");
        lblAlertaNueva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelSuperior.add(lblAlertaNueva);

        panelAgregaEdita.add(panelSuperior, java.awt.BorderLayout.NORTH);

        scrollPanelMedio.setPreferredSize(new java.awt.Dimension(502, 502));

        panelMedio.setMaximumSize(new java.awt.Dimension(500, 550));
        panelMedio.setMinimumSize(new java.awt.Dimension(480, 520));
        panelMedio.setPreferredSize(new java.awt.Dimension(480, 520));
        panelMedio.setScrollableTracksViewportHeight(false);
        panelMedio.setScrollableTracksViewportWidth(false);
        panelMedio.setLayout(new javax.swing.BoxLayout(panelMedio, javax.swing.BoxLayout.PAGE_AXIS));

        panelDatosAlerta.setMaximumSize(new java.awt.Dimension(500, 100));
        panelDatosAlerta.setMinimumSize(new java.awt.Dimension(500, 100));
        panelDatosAlerta.setLayout(new java.awt.GridLayout(3, 1));

        panelNombre.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        panelLblNombre.setMaximumSize(new java.awt.Dimension(100, 33));
        panelLblNombre.setMinimumSize(new java.awt.Dimension(100, 33));
        panelLblNombre.setPreferredSize(new java.awt.Dimension(100, 33));
        panelLblNombre.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblNombre.setText("Nombre");
        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelLblNombre.add(lblNombre);

        panelNombre.add(panelLblNombre);

        panelCampoNombre.setMaximumSize(new java.awt.Dimension(400, 33));
        panelCampoNombre.setMinimumSize(new java.awt.Dimension(350, 33));
        panelCampoNombre.setPreferredSize(new java.awt.Dimension(350, 33));
        panelCampoNombre.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        campoNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNombre.setMaximumSize(new java.awt.Dimension(300, 23));
        campoNombre.setMinimumSize(new java.awt.Dimension(300, 23));
        campoNombre.setPreferredSize(new java.awt.Dimension(300, 23));
        panelCampoNombre.add(campoNombre);

        panelNombre.add(panelCampoNombre);

        panelDatosAlerta.add(panelNombre);

        panelEstado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        panelLblEstado.setMaximumSize(new java.awt.Dimension(100, 33));
        panelLblEstado.setMinimumSize(new java.awt.Dimension(100, 33));
        panelLblEstado.setPreferredSize(new java.awt.Dimension(100, 33));
        panelLblEstado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblEstado.setText("Estado");
        lblEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelLblEstado.add(lblEstado);

        panelEstado.add(panelLblEstado);

        panelComboEstado.setMaximumSize(new java.awt.Dimension(400, 33));
        panelComboEstado.setMinimumSize(new java.awt.Dimension(350, 33));
        panelComboEstado.setPreferredSize(new java.awt.Dimension(350, 33));
        panelComboEstado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        comboEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Desactivada", "Activada" }));
        comboEstado.setMaximumSize(new java.awt.Dimension(150, 23));
        comboEstado.setMinimumSize(new java.awt.Dimension(150, 23));
        comboEstado.setPreferredSize(new java.awt.Dimension(150, 23));
        panelComboEstado.add(comboEstado);

        panelEstado.add(panelComboEstado);

        panelDatosAlerta.add(panelEstado);

        panelTxtCondiciones.setMinimumSize(new java.awt.Dimension(370, 20));
        panelTxtCondiciones.setPreferredSize(new java.awt.Dimension(370, 15));
        panelTxtCondiciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblCondiciones.setText("Condiciones que deben cumplirse para que ocurra la alerta:");
        lblCondiciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelTxtCondiciones.add(lblCondiciones);

        panelDatosAlerta.add(panelTxtCondiciones);

        panelMedio.add(panelDatosAlerta);

        panelTablaCondiciones.setPreferredSize(new java.awt.Dimension(452, 180));
        panelTablaCondiciones.setLayout(new javax.swing.BoxLayout(panelTablaCondiciones, javax.swing.BoxLayout.PAGE_AXIS));

        scrollTablaCondiciones.setMaximumSize(new java.awt.Dimension(452, 180));
        scrollTablaCondiciones.setPreferredSize(new java.awt.Dimension(452, 150));

        tablaCondiciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "null", "Descripcion", "Accion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCondiciones.setColumnSelectionAllowed(true);
        tablaCondiciones.setPreferredSize(new java.awt.Dimension(400, 72));
        tablaCondiciones.getTableHeader().setReorderingAllowed(false);
        tablaCondiciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCondicionesMouseClicked(evt);
            }
        });
        scrollTablaCondiciones.setViewportView(tablaCondiciones);
        tablaCondiciones.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaCondiciones.getColumnModel().getColumn(0).setMinWidth(0);
        tablaCondiciones.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaCondiciones.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaCondiciones.getColumnModel().getColumn(1).setMinWidth(500);
        tablaCondiciones.getColumnModel().getColumn(1).setPreferredWidth(500);
        tablaCondiciones.getColumnModel().getColumn(1).setMaxWidth(500);
        tablaCondiciones.getColumnModel().getColumn(2).setMinWidth(0);
        tablaCondiciones.getColumnModel().getColumn(2).setPreferredWidth(0);
        tablaCondiciones.getColumnModel().getColumn(2).setMaxWidth(0);

        panelTablaCondiciones.add(scrollTablaCondiciones);

        panelAccionesCondicion.setMaximumSize(new java.awt.Dimension(450, 30));
        panelAccionesCondicion.setMinimumSize(new java.awt.Dimension(450, 30));
        panelAccionesCondicion.setPreferredSize(new java.awt.Dimension(450, 30));
        panelAccionesCondicion.setLayout(new java.awt.GridLayout(1, 2));

        lblAccionesCondicion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAccionesCondicion.setText("Acciones condición seleccionada");
        lblAccionesCondicion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelAccionesCondicion.add(lblAccionesCondicion);

        panelAcciones.setMinimumSize(new java.awt.Dimension(62, 17));
        panelAcciones.setPreferredSize(new java.awt.Dimension(62, 17));
        panelAcciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tabla-icono-editar.png"))); // NOI18N
        btnModificar.setText("");
        btnModificar.setToolTipText("Modificar campaña");
        btnModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelAcciones.add(btnModificar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tabla-icono-eliminar.png"))); // NOI18N
        btnEliminar.setText("");
        btnEliminar.setToolTipText("Eliminar campaña");
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelAcciones.add(btnEliminar);

        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tabla-icono-insertar.png"))); // NOI18N
        btnInsertar.setText("");
        btnInsertar.setToolTipText("Eliminar campaña");
        btnInsertar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        panelAcciones.add(btnInsertar);

        panelAccionesCondicion.add(panelAcciones);

        panelTablaCondiciones.add(panelAccionesCondicion);

        panelMedio.add(panelTablaCondiciones);

        panelRelleno.setPreferredSize(new java.awt.Dimension(450, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelRelleno.add(jLabel1);

        panelMedio.add(panelRelleno);

        panelNuevaCondicion.setAlignmentY(3.0F);
        panelNuevaCondicion.setMaximumSize(new java.awt.Dimension(500, 200));
        panelNuevaCondicion.setMinimumSize(new java.awt.Dimension(500, 200));
        panelNuevaCondicion.setPreferredSize(new java.awt.Dimension(500, 200));
        panelNuevaCondicion.setLayout(new javax.swing.BoxLayout(panelNuevaCondicion, javax.swing.BoxLayout.PAGE_AXIS));

        panelDatosCondicion.setMaximumSize(new java.awt.Dimension(500, 170));
        panelDatosCondicion.setMinimumSize(new java.awt.Dimension(500, 170));
        panelDatosCondicion.setLayout(new java.awt.GridLayout(5, 1));

        panelVariable.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        panelLblVariable.setMaximumSize(new java.awt.Dimension(150, 34));
        panelLblVariable.setMinimumSize(new java.awt.Dimension(150, 34));
        panelLblVariable.setPreferredSize(new java.awt.Dimension(150, 34));
        panelLblVariable.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblVariable.setText("Variable a monitorear");
        lblVariable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelLblVariable.add(lblVariable);

        panelVariable.add(panelLblVariable);

        panelComboVariable.setMaximumSize(new java.awt.Dimension(350, 34));
        panelComboVariable.setMinimumSize(new java.awt.Dimension(300, 34));
        panelComboVariable.setPreferredSize(new java.awt.Dimension(300, 34));
        panelComboVariable.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setMaximumSize(new java.awt.Dimension(200, 23));
        jComboBox1.setMinimumSize(new java.awt.Dimension(200, 23));
        jComboBox1.setPreferredSize(new java.awt.Dimension(200, 23));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jComboBox1InputMethodTextChanged(evt);
            }
        });
        panelComboVariable.add(jComboBox1);

        panelVariable.add(panelComboVariable);

        panelDatosCondicion.add(panelVariable);

        panelRelacion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        panelLblRelacion.setMaximumSize(new java.awt.Dimension(150, 34));
        panelLblRelacion.setMinimumSize(new java.awt.Dimension(150, 34));
        panelLblRelacion.setPreferredSize(new java.awt.Dimension(150, 34));
        panelLblRelacion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblRelacion.setText("Relacion de variable");
        lblRelacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelLblRelacion.add(lblRelacion);

        panelRelacion.add(panelLblRelacion);

        panelComboRelacion.setMaximumSize(new java.awt.Dimension(350, 34));
        panelComboRelacion.setMinimumSize(new java.awt.Dimension(300, 34));
        panelComboRelacion.setPreferredSize(new java.awt.Dimension(300, 34));
        panelComboRelacion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setMaximumSize(new java.awt.Dimension(160, 23));
        jComboBox2.setMinimumSize(new java.awt.Dimension(160, 23));
        jComboBox2.setPreferredSize(new java.awt.Dimension(150, 23));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        panelComboRelacion.add(jComboBox2);

        panelRelacion.add(panelComboRelacion);

        panelDatosCondicion.add(panelRelacion);

        panelValMin.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        panelLblValMin.setMaximumSize(new java.awt.Dimension(150, 34));
        panelLblValMin.setMinimumSize(new java.awt.Dimension(150, 34));
        panelLblValMin.setPreferredSize(new java.awt.Dimension(150, 34));
        panelLblValMin.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblValMin.setText("Valor mínimo");
        lblValMin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelLblValMin.add(lblValMin);

        panelValMin.add(panelLblValMin);

        panelCampoValMin.setMaximumSize(new java.awt.Dimension(350, 34));
        panelCampoValMin.setMinimumSize(new java.awt.Dimension(300, 34));
        panelCampoValMin.setPreferredSize(new java.awt.Dimension(300, 34));
        panelCampoValMin.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setMaximumSize(new java.awt.Dimension(160, 23));
        jTextField1.setMinimumSize(new java.awt.Dimension(160, 23));
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 23));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panelCampoValMin.add(jTextField1);
        panelCampoValMin.add(jLabel3);

        jLabel6.setText(" ->");
        panelCampoValMin.add(jLabel6);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        panelCampoValMin.add(jLabel4);

        panelValMin.add(panelCampoValMin);

        panelDatosCondicion.add(panelValMin);

        panelValMax.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        panelLblValMax.setMaximumSize(new java.awt.Dimension(150, 34));
        panelLblValMax.setMinimumSize(new java.awt.Dimension(150, 34));
        panelLblValMax.setPreferredSize(new java.awt.Dimension(150, 34));
        panelLblValMax.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblValMax.setText("Valor máximo");
        lblValMax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelLblValMax.add(lblValMax);

        panelValMax.add(panelLblValMax);

        panelCampoValMax.setMaximumSize(new java.awt.Dimension(350, 34));
        panelCampoValMax.setMinimumSize(new java.awt.Dimension(300, 34));
        panelCampoValMax.setPreferredSize(new java.awt.Dimension(300, 34));
        panelCampoValMax.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setMaximumSize(new java.awt.Dimension(160, 23));
        jTextField2.setMinimumSize(new java.awt.Dimension(160, 23));
        jTextField2.setPreferredSize(new java.awt.Dimension(150, 23));
        panelCampoValMax.add(jTextField2);
        panelCampoValMax.add(jLabel2);

        jLabel7.setText(" ->");
        panelCampoValMax.add(jLabel7);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        panelCampoValMax.add(jLabel5);

        panelValMax.add(panelCampoValMax);

        panelDatosCondicion.add(panelValMax);

        btnAgregar.setText("Agregar Condición");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelBtnAgrega.add(btnAgregar);

        panelDatosCondicion.add(panelBtnAgrega);

        panelNuevaCondicion.add(panelDatosCondicion);

        panelMedio.add(panelNuevaCondicion);

        scrollPanelMedio.setViewportView(panelMedio);

        panelAgregaEdita.add(scrollPanelMedio, java.awt.BorderLayout.LINE_END);

        panelInferior.setMaximumSize(new java.awt.Dimension(500, 50));
        panelInferior.setMinimumSize(new java.awt.Dimension(500, 50));
        panelInferior.setPreferredSize(new java.awt.Dimension(500, 50));
        panelInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        btnVolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        panelInferior.add(btnVolver);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelInferior.add(btnGuardar);

        panelAgregaEdita.add(panelInferior, java.awt.BorderLayout.SOUTH);

        add(panelAgregaEdita, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    agregaCondicionTabla();    
    setModificandoCondicion(false);
    setGuardandoCondicion(true);
    controlaPanelNuevaCondicion(false);
    controlaPanelAccionesCondicion();
    setGuardandoCondicion(false);
    
    
}//GEN-LAST:event_btnAgregarActionPerformed

private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
// TODO add your handling code here:
    setVisible(false);
    PanelOpcAlertas.getInstance().actualizaLabelCantOcurNoVistas();
    PanelOpcAlertas.getInstance().getPanelAlertasPpal().setVisible(true);
}//GEN-LAST:event_btnVolverActionPerformed

private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    setModificandoCondicion(true);
    setGuiModificarFilaElegida();
    cargaPanelConfigCondicion();
    controlaPanelAccionesCondicion();
}//GEN-LAST:event_btnModificarActionPerformed

private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    int fila=tablaCondiciones.getSelectedRow();
    String txtPregunta = "Está por eliminar una condición, está usted seguro?";
    if (JOptionPane.showConfirmDialog(null, txtPregunta, "Eliminar condición seleccionada", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
        controllers.ControllerAlertas.getInstance().borrarCondicion(getIdDeCondicionSeleccionada());
        eliminaUnaFilaCondicion(fila);
        controlaPanelAccionesCondicion();
    }
}//GEN-LAST:event_btnEliminarActionPerformed

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
if (!configCombo1) {
        cambioVariableAct();
        actualizaPanelValoresUnidades();
    }
}//GEN-LAST:event_jComboBox1ActionPerformed

private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
    if (!configCombo1) {
        cambioVariableAct();

        actualizaPanelValoresUnidades();
    }
    
}//GEN-LAST:event_jComboBox1ItemStateChanged

private void jComboBox1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBox1InputMethodTextChanged

}//GEN-LAST:event_jComboBox1InputMethodTextChanged

private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
    if (!configCombo2) {
        cambioRelacionAct();
        actualizaPanelValoresUnidades();
    }
}//GEN-LAST:event_jComboBox2ActionPerformed

private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
    cargaPanelConfigCondicion();
    controlaPanelNuevaCondicion(true);
    modificandoCondicion=false;
    jLabel1.setText("Ingresar datos de condición");
}//GEN-LAST:event_btnInsertarActionPerformed

private void tablaCondicionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCondicionesMouseClicked
    controlaPanelAccionesCondicion();
}//GEN-LAST:event_tablaCondicionesMouseClicked

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String estado;                                               
    if (validaCampos()) {
   
        if (comboEstado.getSelectedIndex()==0){
            estado="Desactivada";
            }
        else{
        estado="Activada";
        }
        if (!PanelOpcAlertas.getInstance().isModificandoAlerta()){
            if (controllers.ControllerAlertas.getInstance().nuevaAlerta(campoNombre.getText(), controllers.ControllerAlertas.getInstance().creaMensaje() , estado,controllers.ControllerAlertas.getInstance().getCondicionesAct())) {
                JOptionPane.showMessageDialog(null, "Alerta guardada correctamente");
                controllers.ControllerAlertas.getInstance().alertasOn();
                btnVolverActionPerformed(null);              
            } else {
                JOptionPane.showMessageDialog(null, "Hubo un error al intentar guardar Alerta");
            }
        }
            else{
                if (controllers.ControllerAlertas.getInstance().modificarAlerta(controllers.ControllerAlertas.getInstance().getAlertaAct().getId(),campoNombre.getText(), controllers.ControllerAlertas.getInstance().creaMensaje() , estado,controllers.ControllerAlertas.getInstance().getCondicionesAct())) {
                JOptionPane.showMessageDialog(null, "Alerta guardada correctamente");
                controllers.ControllerAlertas.getInstance().alertasOn();                
                btnVolverActionPerformed(null);
                } else {
                JOptionPane.showMessageDialog(null, "Hubo un error al intentar guardar Alerta");
                }
            }
        }
    PanelOpcAlertas.getInstance().setModificandoAlerta(false);
  
}//GEN-LAST:event_btnGuardarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private org.jdesktop.swingx.JXHyperlink btnEliminar;
    private javax.swing.JButton btnGuardar;
    private org.jdesktop.swingx.JXHyperlink btnInsertar;
    private org.jdesktop.swingx.JXHyperlink btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JComboBox comboEstado;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private org.jdesktop.swingx.JXLabel lblAccionesCondicion;
    private org.jdesktop.swingx.JXLabel lblAlertaNueva;
    private org.jdesktop.swingx.JXLabel lblCondiciones;
    private org.jdesktop.swingx.JXLabel lblEstado;
    private org.jdesktop.swingx.JXLabel lblNombre;
    private org.jdesktop.swingx.JXLabel lblRelacion;
    private org.jdesktop.swingx.JXLabel lblValMax;
    private org.jdesktop.swingx.JXLabel lblValMin;
    private org.jdesktop.swingx.JXLabel lblVariable;
    private org.jdesktop.swingx.JXPanel panelAcciones;
    private org.jdesktop.swingx.JXPanel panelAccionesCondicion;
    private org.jdesktop.swingx.JXPanel panelAgregaEdita;
    private org.jdesktop.swingx.JXPanel panelBtnAgrega;
    private org.jdesktop.swingx.JXPanel panelCampoNombre;
    private org.jdesktop.swingx.JXPanel panelCampoValMax;
    private org.jdesktop.swingx.JXPanel panelCampoValMin;
    private org.jdesktop.swingx.JXPanel panelComboEstado;
    private org.jdesktop.swingx.JXPanel panelComboRelacion;
    private org.jdesktop.swingx.JXPanel panelComboVariable;
    private org.jdesktop.swingx.JXPanel panelDatosAlerta;
    private org.jdesktop.swingx.JXPanel panelDatosCondicion;
    private org.jdesktop.swingx.JXPanel panelEstado;
    private org.jdesktop.swingx.JXPanel panelInferior;
    private org.jdesktop.swingx.JXPanel panelLblEstado;
    private org.jdesktop.swingx.JXPanel panelLblNombre;
    private org.jdesktop.swingx.JXPanel panelLblRelacion;
    private org.jdesktop.swingx.JXPanel panelLblValMax;
    private org.jdesktop.swingx.JXPanel panelLblValMin;
    private org.jdesktop.swingx.JXPanel panelLblVariable;
    private org.jdesktop.swingx.JXPanel panelMedio;
    private org.jdesktop.swingx.JXPanel panelNombre;
    private org.jdesktop.swingx.JXPanel panelNuevaCondicion;
    private org.jdesktop.swingx.JXPanel panelRelacion;
    private org.jdesktop.swingx.JXPanel panelRelleno;
    private org.jdesktop.swingx.JXPanel panelSuperior;
    private org.jdesktop.swingx.JXPanel panelTablaCondiciones;
    private org.jdesktop.swingx.JXPanel panelTxtCondiciones;
    private org.jdesktop.swingx.JXPanel panelValMax;
    private org.jdesktop.swingx.JXPanel panelValMin;
    private org.jdesktop.swingx.JXPanel panelVariable;
    private javax.swing.JScrollPane scrollPanelMedio;
    private javax.swing.JScrollPane scrollTablaCondiciones;
    private org.jdesktop.swingx.JXTable tablaCondiciones;
    // End of variables declaration//GEN-END:variables
 
    private void inicializador() {

        idProvCondicion=10000;
        modificandoCondicion=false;
        NRO_COL_ID_CONDICION=0;
        NRO_COL_DESCRIPCION=1;
        NRO_COL_ACCIONES=2;
        controlaPanelNuevaCondicion(false);
        cantColumnas=3;        
        modeloTabla = (DefaultTableModel) tablaCondiciones.getModel();
        tablaCondiciones.setModel(modeloTabla);
        cargaIconosDeBotones();
        cargaGrillaCondiciones();
        cargaPanelConfigCondicion();
        varRelCargadas=true;
        controlaPanelAccionesCondicion();

    }
    
    private void cargaIconosDeBotones() {
        //btnModificar.setIcon(new javax.swing.ImageIcon("imgs//iconos//tabla-icono-editar.png"));
        //btnEliminar.setIcon(new javax.swing.ImageIcon("imgs//iconos//tabla-icono-eliminar.png"));
        //btnInsertar.setIcon(new javax.swing.ImageIcon("imgs//iconos//tabla-icono-insertar.png"));
        //btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("imgs//iconos//tabla-icono-insertar.png"))); // NOI18N
    }
    
    public static PanelOpcAlertasAgregaEdita getInstance() {
       if (unicaInstancia == null) {
          unicaInstancia = new PanelOpcAlertasAgregaEdita();          
       }
       return unicaInstancia;
    }

    public void cargaAlertaEditar(int idDeAlertaSeleccionada) {
    
    if (idDeAlertaSeleccionada!=-1){
        controllers.ControllerAlertas.getInstance().setAlertaAct(AdministraAlertas.getInstance().getAlerta(idDeAlertaSeleccionada));        
        controllers.ControllerAlertas.getInstance().setCondicionesAct(controllers.ControllerAlertas.getInstance().getAlertaAct().getCondiciones());
        campoNombre.setText(controllers.ControllerAlertas.getInstance().getAlertaAct().getTitulo());
        boolean estado=controllers.ControllerAlertas.getInstance().getAlertaAct().isEstado();
        if (estado) {
            comboEstado.setSelectedIndex(1);
        } else {
            comboEstado.setSelectedIndex(0);
        }
        
        controlaPanelNuevaCondicion(false);
        cargaGrillaCondiciones();
    }else{
        controllers.ControllerAlertas.getInstance().setAlertaAct(null);        
        controllers.ControllerAlertas.getInstance().setCondicionesAct(null);
        campoNombre.setText("");
        comboEstado.setSelectedIndex(1);
        vaciaTabla();
    }
        
        //cargaPanelConfigCondicion();
        //controlaPanelAccionesCondicion();
    }

    public void vaciaTabla() {
        modeloTabla.setRowCount(0);
    }

    /**
     * @return the alertaAct
     */
    public Alerta getAlertaAct() {
        return alertaAct;
    }

    /**
     * @param alertaAct the alertaAct to set
     */
    public void setAlertaAct(Alerta alertaAct) {
        this.alertaAct = alertaAct;
    }

    public void agregaUnaFilaCondicion(int id, String descripcion) {
        Object[] fila = new Object[cantColumnas]; //creamos la fila
        fila[NRO_COL_ACCIONES]=panelAcciones;
        fila[NRO_COL_ID_CONDICION]=id;
        fila[NRO_COL_DESCRIPCION]=descripcion;
        modeloTabla.addRow(fila);
    }
    
        public void eliminaUnaFilaCondicion(int fila) {

        modeloTabla.removeRow(fila);
    }

        private void cargaGrillaCondiciones() {
        vaciaTabla();
        if (!(controllers.ControllerAlertas.getInstance().getAlertaAct()==null)){
        ArrayList<modelo.alertas.Condicion> condiciones = controllers.ControllerAlertas.getInstance().getAlertaAct().getCondiciones();
        /*
        if ((condiciones == null) || (condiciones.isEmpty()) ) {
            modelo.alertas.AdministraAlertas.getInstance().leerAlertasDeLaDB();
            alertas = modelo.alertas.AdministraAlertas.getInstance().getAlertas();            
        }   
         */
         
        if ((!(condiciones == null)) && (condiciones.size() > 0)) {
            // while (), pongo cada objeto Condicion en la grilla de condiciones                    
            int i = 0;
            while (i < condiciones.size()) {
                agregaUnaFilaCondicion(
                        condiciones.get(i).getId(),
                        condiciones.get(i).getDescripcion()
                        );
                i++;
            }
            
        }
        }
    }
    
    private void controlaPanelAccionesCondicion() {
        
        boolean estado;
        
        if ((modeloTabla.getRowCount()>0) && (getIdDeCondicionSeleccionada()>=0) ){
           estado = true;
        }
        else { 
            estado = false; }
        lblAccionesCondicion.setEnabled(estado);
        btnInsertar.setEnabled(true);
        btnEliminar.setEnabled(estado);
        btnModificar.setEnabled(estado);  
        if (isModificandoCondicion()){
            btnInsertar.setVisible(false);
            btnModificar.setVisible(false);
            btnEliminar.setVisible(false);
            tablaCondiciones.setEnabled(false);
        }
        else
            { 
              btnModificar.setVisible(true);
              btnEliminar.setVisible(true);
              btnInsertar.setVisible(true);
              tablaCondiciones.setEnabled(true);            
            }
    }

    /**
     * @return the modificandoCondicion
     */
    public boolean isModificandoCondicion() {
        return modificandoCondicion;
    }

    /**
     * @param modificandoCondicion the modificandoCondicion to set
     */
    public void setModificandoCondicion(boolean modificandoCondicion) {
        this.modificandoCondicion = modificandoCondicion;
    }

    private int getIdDeCondicionSeleccionada() {
        
        int salida = -1;
        int filaSeleccionada = tablaCondiciones.getSelectedRow();
        if (filaSeleccionada>=0){
            salida = (Integer) modeloTabla.getValueAt(filaSeleccionada, NRO_COL_ID_CONDICION);
        }                
        return salida;
    }

    private void setGuiModificarFilaElegida() {
       int filaSeleccionada = tablaCondiciones.getSelectedRow();
       if (filaSeleccionada>=0){
           //Pendiente: Mostrar panel para modificacion de Condicion elegida
           
           btnAgregar.setText("Guardar");
           jLabel1.setText("Modificar datos de condición");
           controlaPanelNuevaCondicion(true);
           int indexCondicion=Integer.valueOf(String.valueOf(modeloTabla.getValueAt(filaSeleccionada,NRO_COL_ID_CONDICION)));
           
           controllers.ControllerAlertas.getInstance().cambiaDatosActuales(indexCondicion);
           cargaPanelConfigCondicion();
       }
    }

    private void cargaPanelConfigCondicion() {
        
        
        configCombo1=true;
        configCombo2=true;
        
        cargaComboVariables();
        cargaComboRelacion();
        
        actualizaPanelValoresUnidades();
        configCombo1=false;
        configCombo2=false;
        
        
    }

    private void agregaUnItemVariable(int id, String nombre) {
        jComboBox1.addItem(nombre);
    }

    private void cargaComboVariables() {
        
        //Obtengo todas las variables de la BD
        //jComboBox1.removeAllItems();
        if ((!modificandoCondicion) && (!varRelCargadas)){
        ControllerAlertas.getInstance().leeVariablesDB();
        variables = controllers.ControllerAlertas.getInstance().getVariables();
 
        if ((!(variables == null)) && (variables.size() > 0)) {
            // while (), pongo cada objeto Condicion en la grilla de condiciones                    
            int i = 0;
            while (i < variables.size()) {
                agregaUnItemVariable(
                        variables.get(i).getId(),
                        variables.get(i).getNombre());
                i++;
            }
        }
        controllers.ControllerAlertas.getInstance().setVariableAct(variables.get(0));
        }else{
            jComboBox1.setSelectedIndex(controllers.ControllerAlertas.getInstance().getVariableAct().getId()-1);
        }
    }

    private void cargaComboRelacion() {
                
        //Obtengo todas las relaciones de la BD
        if ((!modificandoCondicion) && (!varRelCargadas)){
        ControllerAlertas.getInstance().leeRelacionesDB(controllers.ControllerAlertas.getInstance().getVariableAct().getId());
        relaciones = controllers.ControllerAlertas.getInstance().getRelaciones();
 
        if ((!(relaciones == null)) && (relaciones.size() > 0)) {
            // while (), pongo cada objeto Condicion en la grilla de condiciones                    
            int i = 0;
            while (i < relaciones.size()) {
                agregaUnItemRelacion(
                        relaciones.get(i).getId(),
                        relaciones.get(i).getDescripcion(),
                        relaciones.get(i).getCantValores());
                i++;
            }
        }
        controllers.ControllerAlertas.getInstance().setRelacionAct(relaciones.get(0));
        }else{
            jComboBox2.setSelectedIndex(controllers.ControllerAlertas.getInstance().getRelacionAct().getId()-1);
        
        }
    }

    private void agregaUnItemRelacion(int id, String descripcion, int cantValores) {
        jComboBox2.addItem(descripcion);
    }

    private void actualizaPanelValoresUnidades() {
        
        if (controllers.ControllerAlertas.getInstance().getRelacionAct().getCantValores()==1){
            //panelValMax.disable();            

    
                jTextField2.setEnabled(false);
                jLabel2.setEnabled(false);//Corresponde a valor Max
                jLabel5.setEnabled(false);//Corresponde a valor Max
                jLabel7.setEnabled(false);//Corresponde a valor Max
                lblValMax.setEnabled(false);
                lblValMin.setText("Valor");
                lblValMax.setText("Valor");   
                jLabel3.setEnabled(true);//Corresponde a valor Min
                jLabel4.setEnabled(true);//Corresponde a valor Min
                jLabel6.setEnabled(true);//Corresponde a valor Min

 
            Condicion condicionAct=controllers.ControllerAlertas.getInstance().getCondicionAct();
            if ((condicionAct!=null) && (isModificandoCondicion())){
                jTextField1.setText(condicionAct.getValorMinimo());
            }
            
        }else{

    
                jTextField2.setEnabled(true);
                jLabel2.setEnabled(true);//Corresponde a ValMax
                jLabel5.setEnabled(true);//Corresponde a ValMax
                jLabel7.setEnabled(true);//Corresponde a ValMax
                lblValMax.setEnabled(true);
                lblValMin.setText("Valor");
                lblValMax.setText("Valor");       
                lblValMax.setEnabled(true);


            Condicion condicionAct=controllers.ControllerAlertas.getInstance().getCondicionAct();
            if ((condicionAct!=null)&& (isModificandoCondicion())){
                jTextField1.setText(condicionAct.getValorMinimo());
                jTextField2.setText(condicionAct.getValorMaximo());                      
            }

            
        }
        jLabel2.setText(controllers.ControllerAlertas.getInstance().getVariableAct().getUnidad());
        jLabel3.setText(controllers.ControllerAlertas.getInstance().getVariableAct().getUnidad());
        jLabel4.setText(controllers.ControllerAlertas.getInstance().getVariableAct().getEjemplo());
        jLabel5.setText(controllers.ControllerAlertas.getInstance().getVariableAct().getEjemplo());
    }

    private void cambioVariableAct() {
        controllers.ControllerAlertas.getInstance().setVariableAct(variables.get(jComboBox1.getSelectedIndex()));
    }

    private void cambioRelacionAct() {
        controllers.ControllerAlertas.getInstance().setRelacionAct(relaciones.get(jComboBox2.getSelectedIndex()));
    }

    public void agregaCondicionTabla(){
        
        if (validaCamposCondicion()){
        
        if (isModificandoCondicion()){
                   
            int filaSeleccionada = tablaCondiciones.getSelectedRow();
            int backIdProvCondicion=idProvCondicion;
            idProvCondicion=Integer.valueOf(String.valueOf(modeloTabla.getValueAt(filaSeleccionada,NRO_COL_ID_CONDICION)));
            
            int cantValores=controllers.ControllerAlertas.getInstance().getRelacionAct().getCantValores();
            String descripcion="";
            String valorMin= jTextField1.getText();
            
            if (cantValores==1){
                if (controllers.ControllerAlertas.getInstance().getVariableAct().getId()==9){
                    descripcion=""+controllers.ControllerAlertas.getInstance().getVariableAct().getNombre()+" "+controllers.ControllerAlertas.getInstance().getRelacionAct().getDescripcion()+" "+jTextField1.getText()+" ";
                    controllers.ControllerAlertas.getInstance().agregaCondicionAct(idProvCondicion,controllers.ControllerAlertas.getInstance().getRelacionAct().getId(), controllers.ControllerAlertas.getInstance().getVariableAct().getId(), valorMin, "", descripcion);  
                }else{
                    descripcion=""+controllers.ControllerAlertas.getInstance().getVariableAct().getNombre()+" "+controllers.ControllerAlertas.getInstance().getRelacionAct().getDescripcion()+" "+jTextField1.getText()+" "+controllers.ControllerAlertas.getInstance().getVariableAct().getUnidad();
                    controllers.ControllerAlertas.getInstance().agregaCondicionAct(idProvCondicion,controllers.ControllerAlertas.getInstance().getRelacionAct().getId(), controllers.ControllerAlertas.getInstance().getVariableAct().getId(), valorMin, "", descripcion);          
                }
                }else{
                String valorMax= jTextField2.getText();
                if (controllers.ControllerAlertas.getInstance().getVariableAct().getId()==9){
                    descripcion=""+controllers.ControllerAlertas.getInstance().getVariableAct().getNombre()+" "+controllers.ControllerAlertas.getInstance().getRelacionAct().getDescripcion()+" "+jTextField1.getText()+" y "+jTextField2.getText()+"";             
                    controllers.ControllerAlertas.getInstance().agregaCondicionAct(idProvCondicion,controllers.ControllerAlertas.getInstance().getRelacionAct().getId(), controllers.ControllerAlertas.getInstance().getVariableAct().getId(), valorMin, valorMax, descripcion);    
            
                }else{
                    descripcion=""+controllers.ControllerAlertas.getInstance().getVariableAct().getNombre()+" "+controllers.ControllerAlertas.getInstance().getRelacionAct().getDescripcion()+" "+jTextField1.getText()+" "+controllers.ControllerAlertas.getInstance().getVariableAct().getUnidad()+" y "+jTextField2.getText()+" "+controllers.ControllerAlertas.getInstance().getVariableAct().getUnidad();             
                    controllers.ControllerAlertas.getInstance().agregaCondicionAct(idProvCondicion,controllers.ControllerAlertas.getInstance().getRelacionAct().getId(), controllers.ControllerAlertas.getInstance().getVariableAct().getId(), valorMin, valorMax, descripcion);         
                }
                }
            modeloTabla.setValueAt(descripcion,filaSeleccionada,NRO_COL_DESCRIPCION);
            idProvCondicion=backIdProvCondicion+1;
            
                }else{//No se esta modificando una condicion (Nueva)
            
                    int cantValores=controllers.ControllerAlertas.getInstance().getRelacionAct().getCantValores();
                    String descripcion="";
                    String valorMin= jTextField1.getText();

                    if (cantValores==1){
                        if (controllers.ControllerAlertas.getInstance().getVariableAct().getId()==9){//Variable Fecha
                            descripcion=""+controllers.ControllerAlertas.getInstance().getVariableAct().getNombre()+" "+controllers.ControllerAlertas.getInstance().getRelacionAct().getDescripcion()+" "+jTextField1.getText()+" ";
                            controllers.ControllerAlertas.getInstance().agregaCondicionAct(idProvCondicion,controllers.ControllerAlertas.getInstance().getRelacionAct().getId(), controllers.ControllerAlertas.getInstance().getVariableAct().getId(), valorMin, "", descripcion);  
                        }else{
                            descripcion=""+controllers.ControllerAlertas.getInstance().getVariableAct().getNombre()+" "+controllers.ControllerAlertas.getInstance().getRelacionAct().getDescripcion()+" "+jTextField1.getText()+" "+controllers.ControllerAlertas.getInstance().getVariableAct().getUnidad();
                            controllers.ControllerAlertas.getInstance().agregaCondicionAct(idProvCondicion,controllers.ControllerAlertas.getInstance().getRelacionAct().getId(), controllers.ControllerAlertas.getInstance().getVariableAct().getId(), valorMin, "", descripcion);          
                        }
                    }else{
                        String valorMax= jTextField2.getText();
                        if (controllers.ControllerAlertas.getInstance().getVariableAct().getId()==9){
                            descripcion=""+controllers.ControllerAlertas.getInstance().getVariableAct().getNombre()+" "+controllers.ControllerAlertas.getInstance().getRelacionAct().getDescripcion()+" "+jTextField1.getText()+" y "+jTextField2.getText()+"";             
                            controllers.ControllerAlertas.getInstance().agregaCondicionAct(idProvCondicion,controllers.ControllerAlertas.getInstance().getRelacionAct().getId(), controllers.ControllerAlertas.getInstance().getVariableAct().getId(), valorMin, valorMax, descripcion);    

                        }else{
                            descripcion=""+controllers.ControllerAlertas.getInstance().getVariableAct().getNombre()+" "+controllers.ControllerAlertas.getInstance().getRelacionAct().getDescripcion()+" "+jTextField1.getText()+" "+controllers.ControllerAlertas.getInstance().getVariableAct().getUnidad()+" y "+jTextField2.getText()+" "+controllers.ControllerAlertas.getInstance().getVariableAct().getUnidad();             
                            controllers.ControllerAlertas.getInstance().agregaCondicionAct(idProvCondicion,controllers.ControllerAlertas.getInstance().getRelacionAct().getId(), controllers.ControllerAlertas.getInstance().getVariableAct().getId(), valorMin, valorMax, descripcion);         
                        }
                    }
                    agregaUnaFilaCondicion(idProvCondicion,descripcion);
                    idProvCondicion=idProvCondicion+1;
        }
    }    
        
    }

    private void controlaPanelNuevaCondicion(boolean b) {
        
        panelDatosCondicion.setEnabled(b);
        jComboBox1.setVisible(b);
        jComboBox2.setVisible(b);
        jTextField1.setVisible(b);
        jTextField1.setText("");
        jTextField2.setVisible(b);
        jTextField2.setText("");
        lblValMin.setVisible(b);
        lblValMax.setVisible(b);
        lblRelacion.setVisible(b);
        lblVariable.setVisible(b);
        jLabel3.setVisible(b);
        jLabel2.setVisible(b);
        jLabel4.setVisible(b);
        jLabel5.setVisible(b);
        jLabel6.setVisible(b);
        jLabel7.setVisible(b);
        btnAgregar.setVisible(b);
    }

    /**
     * @return the guardandoCondicion
     */
    public boolean isGuardandoCondicion() {
        return guardandoCondicion;
    }

    /**
     * @param guardandoCondicion the guardandoCondicion to set
     */
    public void setGuardandoCondicion(boolean guardandoCondicion) {
        this.guardandoCondicion = guardandoCondicion;
    }

    private boolean validaCampos() {
        boolean camposRequeridos = campoNombre.getText().length() > 0
                && tablaCondiciones.getRowCount()>0;
        if (!(camposRequeridos)) {
            JOptionPane.showMessageDialog(null, "Error! Revise valores necesarios para guardar una Alerta");
        }
        return camposRequeridos;
    }
    
        private boolean validaCamposCondicion() {
        
        boolean camposRequeridos = true;
        
        
            int cantValores=controllers.ControllerAlertas.getInstance().getRelacionAct().getCantValores();        
            if (cantValores==1){
                if (controllers.ControllerAlertas.getInstance().getVariableAct().getId()==9){
                    if (!validaFormatoFechaYhora(jTextField1.getText())){
                        camposRequeridos=false;
                    }
                }else{
                    if (jTextField1.getText().length()<=0){
                        camposRequeridos=false;
                    }
                }     
            }else{
                String valorMax= jTextField2.getText();
                if (controllers.ControllerAlertas.getInstance().getVariableAct().getId()==9){
                    if (!validaFormatoFechaYhora(jTextField1.getText()) || !validaFormatoFechaYhora(jTextField2.getText())  ){
                        camposRequeridos=false;
                    }
                }else{
                    if (jTextField1.getText().length()<=0 || jTextField2.getText().length()<=0){
                        camposRequeridos=false;
                    }
                }        
            } // (cantValores==1)
  
                   
        if (!(camposRequeridos)) {
            JOptionPane.showMessageDialog(null, "Error! Revise valores necesarios para guardar una Alerta");
        }
        return camposRequeridos;
      
    }

        private static boolean validaFormatoFechaYhora(String fecha_intro){  
            try {  
                
                SimpleDateFormat formato_correcto = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");  
                Date fecha_bien = formato_correcto.parse(fecha_intro);   
            } catch (ParseException e) {  
                return false;  
            }  
            return true;  
        }

    
}
