/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelEstado.java
 *
 * Created on 06/04/2012, 13:54:49
 */
package gui;

/**
 *
 * @author Sebastian
 */
public class PanelEstado extends javax.swing.JPanel {

    /** Creates new form PanelEstado */
    public PanelEstado() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        lblEstadoSistema = new java.awt.Label();
        panelCentro = new javax.swing.JPanel();
        panelGps = new javax.swing.JPanel();
        panelGpsSup = new javax.swing.JPanel();
        lblGps = new java.awt.Label();
        panelGpsCentro = new javax.swing.JPanel();
        panelGPSconexionColor = new javax.swing.JPanel();
        GpsEstado = new javax.swing.JPanel();
        panelGPSconexionTxt = new javax.swing.JPanel();
        lblGpsEstado = new java.awt.Label();
        panelGpsInf = new javax.swing.JPanel();
        lblGpsInfoConexion = new java.awt.Label();
        panelInfoGPS = new javax.swing.JPanel();
        lblPuertoGPS = new java.awt.Label();
        lblNroPuertoGPS = new java.awt.Label();
        lblVelocidadGPS = new java.awt.Label();
        lblNroVelocidadGPS = new java.awt.Label();
        panelRellenoGPS = new javax.swing.JPanel();
        panelSonda = new javax.swing.JPanel();
        panelSondaSup = new javax.swing.JPanel();
        lblSonda = new java.awt.Label();
        panelSondaCentro = new javax.swing.JPanel();
        panelSONDAconexionColor = new javax.swing.JPanel();
        SondaEstado = new javax.swing.JPanel();
        panelSONDAconexionTxt = new javax.swing.JPanel();
        lblSondaEstado = new java.awt.Label();
        panelSondaInf = new javax.swing.JPanel();
        lblSondaInfoConexion = new java.awt.Label();
        panelInfoSonda = new javax.swing.JPanel();
        lblPuertoSonda = new java.awt.Label();
        lblNroPuertoSonda = new java.awt.Label();
        lblVelocidadSonda = new java.awt.Label();
        lblNroVelocidadSonda = new java.awt.Label();
        panelRellenoSonda = new javax.swing.JPanel();
        PanelLan = new javax.swing.JPanel();
        panelLanSup = new javax.swing.JPanel();
        lblLan = new java.awt.Label();
        panelLanCentro = new javax.swing.JPanel();
        panelLANconexionColor = new javax.swing.JPanel();
        LanEstado = new javax.swing.JPanel();
        panelLANconexionTxt = new javax.swing.JPanel();
        lblLanEstado = new java.awt.Label();
        panelLanInf = new javax.swing.JPanel();
        lblLanInfoConexion = new java.awt.Label();
        panelInfoLan = new javax.swing.JPanel();
        lblLanIP = new java.awt.Label();
        lblLanIPnro = new java.awt.Label();
        lblLanPuerto = new java.awt.Label();
        lblLanPuertoNro = new java.awt.Label();
        panelRellenoLan = new javax.swing.JPanel();
        panelInferior = new javax.swing.JPanel();
        panelSupIzq = new javax.swing.JPanel();
        lblHistorico = new java.awt.Label();
        panelEstadoHistorico = new javax.swing.JPanel();
        HistoricoEstado = new javax.swing.JPanel();
        lblHistoricoEstado = new java.awt.Label();
        panelSupDer = new javax.swing.JPanel();
        lblInternet = new java.awt.Label();
        panelEstadoInternet = new javax.swing.JPanel();
        InternetEstado = new javax.swing.JPanel();
        panelInfIzq = new javax.swing.JPanel();
        lblAlertas = new java.awt.Label();
        panelEstadoAlertas = new javax.swing.JPanel();
        AlertasEstado = new javax.swing.JPanel();
        lblAlertasEstado = new java.awt.Label();
        panelInfDer = new javax.swing.JPanel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(500, 350));
        setMinimumSize(new java.awt.Dimension(500, 350));
        setPreferredSize(new java.awt.Dimension(500, 350));
        setLayout(new java.awt.BorderLayout());

        panelSuperior.setPreferredSize(new java.awt.Dimension(400, 40));

        lblEstadoSistema.setFont(new java.awt.Font("Arial", 0, 18));
        lblEstadoSistema.setText("Estado del Sistema");
        panelSuperior.add(lblEstadoSistema);

        add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelCentro.setPreferredSize(new java.awt.Dimension(400, 290));
        panelCentro.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        panelGps.setLayout(new java.awt.BorderLayout());

        panelGpsSup.setPreferredSize(new java.awt.Dimension(133, 25));

        lblGps.setFont(new java.awt.Font("Dialog", 1, 14));
        lblGps.setText("GPS");
        panelGpsSup.add(lblGps);

        panelGps.add(panelGpsSup, java.awt.BorderLayout.NORTH);

        panelGpsCentro.setMaximumSize(new java.awt.Dimension(133, 30));
        panelGpsCentro.setMinimumSize(new java.awt.Dimension(133, 30));
        panelGpsCentro.setPreferredSize(new java.awt.Dimension(133, 30));
        panelGpsCentro.setLayout(new javax.swing.BoxLayout(panelGpsCentro, javax.swing.BoxLayout.LINE_AXIS));

        panelGPSconexionColor.setMaximumSize(new java.awt.Dimension(60, 30));
        panelGPSconexionColor.setMinimumSize(new java.awt.Dimension(60, 30));
        panelGPSconexionColor.setPreferredSize(new java.awt.Dimension(60, 30));
        panelGPSconexionColor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        GpsEstado.setBackground(new java.awt.Color(204, 0, 0));
        GpsEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GpsEstado.setMaximumSize(new java.awt.Dimension(30, 20));
        GpsEstado.setMinimumSize(new java.awt.Dimension(30, 20));
        GpsEstado.setPreferredSize(new java.awt.Dimension(30, 20));

        javax.swing.GroupLayout GpsEstadoLayout = new javax.swing.GroupLayout(GpsEstado);
        GpsEstado.setLayout(GpsEstadoLayout);
        GpsEstadoLayout.setHorizontalGroup(
            GpsEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        GpsEstadoLayout.setVerticalGroup(
            GpsEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        panelGPSconexionColor.add(GpsEstado);

        panelGpsCentro.add(panelGPSconexionColor);

        panelGPSconexionTxt.setMaximumSize(new java.awt.Dimension(93, 30));
        panelGPSconexionTxt.setMinimumSize(new java.awt.Dimension(93, 30));
        panelGPSconexionTxt.setPreferredSize(new java.awt.Dimension(93, 30));
        panelGPSconexionTxt.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblGpsEstado.setText("Desconectado");
        panelGPSconexionTxt.add(lblGpsEstado);

        panelGpsCentro.add(panelGPSconexionTxt);

        panelGps.add(panelGpsCentro, java.awt.BorderLayout.CENTER);

        panelGpsInf.setMaximumSize(new java.awt.Dimension(133, 175));
        panelGpsInf.setMinimumSize(new java.awt.Dimension(133, 175));
        panelGpsInf.setPreferredSize(new java.awt.Dimension(133, 175));
        panelGpsInf.setLayout(new javax.swing.BoxLayout(panelGpsInf, javax.swing.BoxLayout.PAGE_AXIS));

        lblGpsInfoConexion.setAlignment(java.awt.Label.CENTER);
        lblGpsInfoConexion.setText("Información de conexión:");
        panelGpsInf.add(lblGpsInfoConexion);

        panelInfoGPS.setMaximumSize(new java.awt.Dimension(186, 70));
        panelInfoGPS.setMinimumSize(new java.awt.Dimension(186, 70));
        panelInfoGPS.setPreferredSize(new java.awt.Dimension(186, 70));
        panelInfoGPS.setLayout(new java.awt.GridLayout(2, 2));

        lblPuertoGPS.setAlignment(java.awt.Label.RIGHT);
        lblPuertoGPS.setText("Puerto: ");
        panelInfoGPS.add(lblPuertoGPS);

        lblNroPuertoGPS.setText("COM X");
        panelInfoGPS.add(lblNroPuertoGPS);

        lblVelocidadGPS.setAlignment(java.awt.Label.RIGHT);
        lblVelocidadGPS.setText("Velocidad: ");
        panelInfoGPS.add(lblVelocidadGPS);

        lblNroVelocidadGPS.setText("XXXX bps");
        panelInfoGPS.add(lblNroVelocidadGPS);

        panelGpsInf.add(panelInfoGPS);

        panelRellenoGPS.setMaximumSize(new java.awt.Dimension(186, 60));
        panelRellenoGPS.setMinimumSize(new java.awt.Dimension(186, 60));
        panelRellenoGPS.setPreferredSize(new java.awt.Dimension(186, 60));

        javax.swing.GroupLayout panelRellenoGPSLayout = new javax.swing.GroupLayout(panelRellenoGPS);
        panelRellenoGPS.setLayout(panelRellenoGPSLayout);
        panelRellenoGPSLayout.setHorizontalGroup(
            panelRellenoGPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        panelRellenoGPSLayout.setVerticalGroup(
            panelRellenoGPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panelGpsInf.add(panelRellenoGPS);

        panelGps.add(panelGpsInf, java.awt.BorderLayout.SOUTH);

        panelCentro.add(panelGps);

        panelSonda.setLayout(new java.awt.BorderLayout());

        panelSondaSup.setPreferredSize(new java.awt.Dimension(133, 25));

        lblSonda.setFont(new java.awt.Font("Dialog", 1, 14));
        lblSonda.setText("SONDA");
        panelSondaSup.add(lblSonda);

        panelSonda.add(panelSondaSup, java.awt.BorderLayout.NORTH);

        panelSondaCentro.setPreferredSize(new java.awt.Dimension(133, 30));
        panelSondaCentro.setLayout(new javax.swing.BoxLayout(panelSondaCentro, javax.swing.BoxLayout.LINE_AXIS));

        panelSONDAconexionColor.setMaximumSize(new java.awt.Dimension(60, 30));
        panelSONDAconexionColor.setMinimumSize(new java.awt.Dimension(60, 30));
        panelSONDAconexionColor.setPreferredSize(new java.awt.Dimension(60, 30));
        panelSONDAconexionColor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        SondaEstado.setBackground(new java.awt.Color(204, 0, 0));
        SondaEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SondaEstado.setMaximumSize(new java.awt.Dimension(30, 20));
        SondaEstado.setMinimumSize(new java.awt.Dimension(30, 20));
        SondaEstado.setPreferredSize(new java.awt.Dimension(30, 20));

        javax.swing.GroupLayout SondaEstadoLayout = new javax.swing.GroupLayout(SondaEstado);
        SondaEstado.setLayout(SondaEstadoLayout);
        SondaEstadoLayout.setHorizontalGroup(
            SondaEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        SondaEstadoLayout.setVerticalGroup(
            SondaEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        panelSONDAconexionColor.add(SondaEstado);

        panelSondaCentro.add(panelSONDAconexionColor);

        panelSONDAconexionTxt.setMaximumSize(new java.awt.Dimension(93, 30));
        panelSONDAconexionTxt.setMinimumSize(new java.awt.Dimension(93, 30));
        panelSONDAconexionTxt.setPreferredSize(new java.awt.Dimension(93, 30));

        lblSondaEstado.setText("Desconectado");
        panelSONDAconexionTxt.add(lblSondaEstado);

        panelSondaCentro.add(panelSONDAconexionTxt);

        panelSonda.add(panelSondaCentro, java.awt.BorderLayout.CENTER);

        panelSondaInf.setMaximumSize(new java.awt.Dimension(133, 175));
        panelSondaInf.setMinimumSize(new java.awt.Dimension(133, 175));
        panelSondaInf.setPreferredSize(new java.awt.Dimension(133, 175));
        panelSondaInf.setRequestFocusEnabled(false);
        panelSondaInf.setLayout(new javax.swing.BoxLayout(panelSondaInf, javax.swing.BoxLayout.PAGE_AXIS));

        lblSondaInfoConexion.setAlignment(java.awt.Label.CENTER);
        lblSondaInfoConexion.setText("Información de conexión:");
        panelSondaInf.add(lblSondaInfoConexion);

        panelInfoSonda.setMaximumSize(new java.awt.Dimension(186, 70));
        panelInfoSonda.setMinimumSize(new java.awt.Dimension(186, 70));
        panelInfoSonda.setPreferredSize(new java.awt.Dimension(186, 70));
        panelInfoSonda.setLayout(new java.awt.GridLayout(2, 2));

        lblPuertoSonda.setAlignment(java.awt.Label.RIGHT);
        lblPuertoSonda.setText("Puerto: ");
        panelInfoSonda.add(lblPuertoSonda);

        lblNroPuertoSonda.setText("COM X");
        panelInfoSonda.add(lblNroPuertoSonda);

        lblVelocidadSonda.setAlignment(java.awt.Label.RIGHT);
        lblVelocidadSonda.setText("Velocidad: ");
        panelInfoSonda.add(lblVelocidadSonda);

        lblNroVelocidadSonda.setText("XXXX bps");
        panelInfoSonda.add(lblNroVelocidadSonda);

        panelSondaInf.add(panelInfoSonda);

        panelRellenoSonda.setMaximumSize(new java.awt.Dimension(186, 60));
        panelRellenoSonda.setMinimumSize(new java.awt.Dimension(186, 60));
        panelRellenoSonda.setPreferredSize(new java.awt.Dimension(186, 60));

        javax.swing.GroupLayout panelRellenoSondaLayout = new javax.swing.GroupLayout(panelRellenoSonda);
        panelRellenoSonda.setLayout(panelRellenoSondaLayout);
        panelRellenoSondaLayout.setHorizontalGroup(
            panelRellenoSondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        panelRellenoSondaLayout.setVerticalGroup(
            panelRellenoSondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panelSondaInf.add(panelRellenoSonda);

        panelSonda.add(panelSondaInf, java.awt.BorderLayout.SOUTH);

        panelCentro.add(panelSonda);

        PanelLan.setLayout(new java.awt.BorderLayout());

        panelLanSup.setPreferredSize(new java.awt.Dimension(133, 25));

        lblLan.setFont(new java.awt.Font("Dialog", 1, 14));
        lblLan.setText("LAN Sonda");
        panelLanSup.add(lblLan);

        PanelLan.add(panelLanSup, java.awt.BorderLayout.NORTH);

        panelLanCentro.setPreferredSize(new java.awt.Dimension(133, 30));
        panelLanCentro.setLayout(new javax.swing.BoxLayout(panelLanCentro, javax.swing.BoxLayout.LINE_AXIS));

        panelLANconexionColor.setMaximumSize(new java.awt.Dimension(60, 30));
        panelLANconexionColor.setMinimumSize(new java.awt.Dimension(60, 30));
        panelLANconexionColor.setPreferredSize(new java.awt.Dimension(60, 30));
        panelLANconexionColor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        LanEstado.setBackground(new java.awt.Color(204, 0, 0));
        LanEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LanEstado.setMaximumSize(new java.awt.Dimension(30, 20));
        LanEstado.setMinimumSize(new java.awt.Dimension(30, 20));
        LanEstado.setPreferredSize(new java.awt.Dimension(30, 20));

        javax.swing.GroupLayout LanEstadoLayout = new javax.swing.GroupLayout(LanEstado);
        LanEstado.setLayout(LanEstadoLayout);
        LanEstadoLayout.setHorizontalGroup(
            LanEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        LanEstadoLayout.setVerticalGroup(
            LanEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        panelLANconexionColor.add(LanEstado);

        panelLanCentro.add(panelLANconexionColor);

        panelLANconexionTxt.setMaximumSize(new java.awt.Dimension(93, 30));
        panelLANconexionTxt.setMinimumSize(new java.awt.Dimension(93, 30));
        panelLANconexionTxt.setPreferredSize(new java.awt.Dimension(93, 30));
        panelLANconexionTxt.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblLanEstado.setText("Desconectado");
        panelLANconexionTxt.add(lblLanEstado);

        panelLanCentro.add(panelLANconexionTxt);

        PanelLan.add(panelLanCentro, java.awt.BorderLayout.CENTER);

        panelLanInf.setMaximumSize(new java.awt.Dimension(133, 175));
        panelLanInf.setMinimumSize(new java.awt.Dimension(133, 175));
        panelLanInf.setPreferredSize(new java.awt.Dimension(133, 175));
        panelLanInf.setLayout(new javax.swing.BoxLayout(panelLanInf, javax.swing.BoxLayout.PAGE_AXIS));

        lblLanInfoConexion.setAlignment(java.awt.Label.CENTER);
        lblLanInfoConexion.setText("Información de conexión:");
        panelLanInf.add(lblLanInfoConexion);

        panelInfoLan.setMaximumSize(new java.awt.Dimension(186, 70));
        panelInfoLan.setMinimumSize(new java.awt.Dimension(186, 70));
        panelInfoLan.setPreferredSize(new java.awt.Dimension(186, 70));
        panelInfoLan.setLayout(new java.awt.GridLayout(2, 2));

        lblLanIP.setAlignment(java.awt.Label.RIGHT);
        lblLanIP.setText("IP: ");
        panelInfoLan.add(lblLanIP);

        lblLanIPnro.setText("0.0.0.0");
        panelInfoLan.add(lblLanIPnro);

        lblLanPuerto.setAlignment(java.awt.Label.RIGHT);
        lblLanPuerto.setText("Puerto: ");
        panelInfoLan.add(lblLanPuerto);

        lblLanPuertoNro.setText("0000");
        panelInfoLan.add(lblLanPuertoNro);

        panelLanInf.add(panelInfoLan);

        panelRellenoLan.setMaximumSize(new java.awt.Dimension(186, 60));
        panelRellenoLan.setMinimumSize(new java.awt.Dimension(186, 60));
        panelRellenoLan.setPreferredSize(new java.awt.Dimension(186, 60));

        javax.swing.GroupLayout panelRellenoLanLayout = new javax.swing.GroupLayout(panelRellenoLan);
        panelRellenoLan.setLayout(panelRellenoLanLayout);
        panelRellenoLanLayout.setHorizontalGroup(
            panelRellenoLanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        panelRellenoLanLayout.setVerticalGroup(
            panelRellenoLanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panelLanInf.add(panelRellenoLan);

        PanelLan.add(panelLanInf, java.awt.BorderLayout.SOUTH);

        panelCentro.add(PanelLan);

        add(panelCentro, java.awt.BorderLayout.CENTER);

        panelInferior.setPreferredSize(new java.awt.Dimension(400, 80));
        panelInferior.setLayout(new java.awt.GridLayout(3, 2, 1, 5));

        panelSupIzq.setLayout(new java.awt.GridLayout());

        lblHistorico.setAlignment(java.awt.Label.RIGHT);
        lblHistorico.setFont(new java.awt.Font("Dialog", 0, 14));
        lblHistorico.setText("Historico");
        panelSupIzq.add(lblHistorico);

        panelEstadoHistorico.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        HistoricoEstado.setBackground(new java.awt.Color(0, 0, 204));
        HistoricoEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HistoricoEstado.setMaximumSize(new java.awt.Dimension(30, 30));
        HistoricoEstado.setPreferredSize(new java.awt.Dimension(30, 30));

        lblHistoricoEstado.setFont(new java.awt.Font("Dialog", 1, 12));
        lblHistoricoEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblHistoricoEstado.setText("OFF");

        javax.swing.GroupLayout HistoricoEstadoLayout = new javax.swing.GroupLayout(HistoricoEstado);
        HistoricoEstado.setLayout(HistoricoEstadoLayout);
        HistoricoEstadoLayout.setHorizontalGroup(
            HistoricoEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
            .addGroup(HistoricoEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HistoricoEstadoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblHistoricoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        HistoricoEstadoLayout.setVerticalGroup(
            HistoricoEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
            .addGroup(HistoricoEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HistoricoEstadoLayout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(lblHistoricoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );

        panelEstadoHistorico.add(HistoricoEstado);

        panelSupIzq.add(panelEstadoHistorico);

        panelInferior.add(panelSupIzq);

        panelSupDer.setLayout(new java.awt.GridLayout(1, 0));

        lblInternet.setAlignment(java.awt.Label.RIGHT);
        lblInternet.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblInternet.setText("Conexión a Internet");
        panelSupDer.add(lblInternet);

        panelEstadoInternet.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 1));

        InternetEstado.setBackground(new java.awt.Color(204, 0, 0));
        InternetEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        InternetEstado.setMaximumSize(new java.awt.Dimension(30, 30));
        InternetEstado.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout InternetEstadoLayout = new javax.swing.GroupLayout(InternetEstado);
        InternetEstado.setLayout(InternetEstadoLayout);
        InternetEstadoLayout.setHorizontalGroup(
            InternetEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        InternetEstadoLayout.setVerticalGroup(
            InternetEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        panelEstadoInternet.add(InternetEstado);

        panelSupDer.add(panelEstadoInternet);

        panelInferior.add(panelSupDer);

        panelInfIzq.setLayout(new java.awt.GridLayout(1, 0));

        lblAlertas.setAlignment(java.awt.Label.RIGHT);
        lblAlertas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblAlertas.setText("Alertas");
        panelInfIzq.add(lblAlertas);

        panelEstadoAlertas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        AlertasEstado.setBackground(new java.awt.Color(0, 0, 204));
        AlertasEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AlertasEstado.setMaximumSize(new java.awt.Dimension(30, 30));
        AlertasEstado.setPreferredSize(new java.awt.Dimension(30, 30));

        lblAlertasEstado.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblAlertasEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblAlertasEstado.setText("OFF");

        javax.swing.GroupLayout AlertasEstadoLayout = new javax.swing.GroupLayout(AlertasEstado);
        AlertasEstado.setLayout(AlertasEstadoLayout);
        AlertasEstadoLayout.setHorizontalGroup(
            AlertasEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
            .addGroup(AlertasEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AlertasEstadoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblAlertasEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        AlertasEstadoLayout.setVerticalGroup(
            AlertasEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
            .addGroup(AlertasEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AlertasEstadoLayout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(lblAlertasEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );

        panelEstadoAlertas.add(AlertasEstado);

        panelInfIzq.add(panelEstadoAlertas);

        panelInferior.add(panelInfIzq);
        panelInferior.add(panelInfDer);

        add(panelInferior, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlertasEstado;
    private javax.swing.JPanel GpsEstado;
    private javax.swing.JPanel HistoricoEstado;
    private javax.swing.JPanel InternetEstado;
    private javax.swing.JPanel LanEstado;
    private javax.swing.JPanel PanelLan;
    private javax.swing.JPanel SondaEstado;
    private java.awt.Label lblAlertas;
    private java.awt.Label lblAlertasEstado;
    private java.awt.Label lblEstadoSistema;
    private java.awt.Label lblGps;
    private java.awt.Label lblGpsEstado;
    private java.awt.Label lblGpsInfoConexion;
    private java.awt.Label lblHistorico;
    private java.awt.Label lblHistoricoEstado;
    private java.awt.Label lblInternet;
    private java.awt.Label lblLan;
    private java.awt.Label lblLanEstado;
    private java.awt.Label lblLanIP;
    private java.awt.Label lblLanIPnro;
    private java.awt.Label lblLanInfoConexion;
    private java.awt.Label lblLanPuerto;
    private java.awt.Label lblLanPuertoNro;
    private java.awt.Label lblNroPuertoGPS;
    private java.awt.Label lblNroPuertoSonda;
    private java.awt.Label lblNroVelocidadGPS;
    private java.awt.Label lblNroVelocidadSonda;
    private java.awt.Label lblPuertoGPS;
    private java.awt.Label lblPuertoSonda;
    private java.awt.Label lblSonda;
    private java.awt.Label lblSondaEstado;
    private java.awt.Label lblSondaInfoConexion;
    private java.awt.Label lblVelocidadGPS;
    private java.awt.Label lblVelocidadSonda;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelEstadoAlertas;
    private javax.swing.JPanel panelEstadoHistorico;
    private javax.swing.JPanel panelEstadoInternet;
    private javax.swing.JPanel panelGPSconexionColor;
    private javax.swing.JPanel panelGPSconexionTxt;
    private javax.swing.JPanel panelGps;
    private javax.swing.JPanel panelGpsCentro;
    private javax.swing.JPanel panelGpsInf;
    private javax.swing.JPanel panelGpsSup;
    private javax.swing.JPanel panelInfDer;
    private javax.swing.JPanel panelInfIzq;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelInfoGPS;
    private javax.swing.JPanel panelInfoLan;
    private javax.swing.JPanel panelInfoSonda;
    private javax.swing.JPanel panelLANconexionColor;
    private javax.swing.JPanel panelLANconexionTxt;
    private javax.swing.JPanel panelLanCentro;
    private javax.swing.JPanel panelLanInf;
    private javax.swing.JPanel panelLanSup;
    private javax.swing.JPanel panelRellenoGPS;
    private javax.swing.JPanel panelRellenoLan;
    private javax.swing.JPanel panelRellenoSonda;
    private javax.swing.JPanel panelSONDAconexionColor;
    private javax.swing.JPanel panelSONDAconexionTxt;
    private javax.swing.JPanel panelSonda;
    private javax.swing.JPanel panelSondaCentro;
    private javax.swing.JPanel panelSondaInf;
    private javax.swing.JPanel panelSondaSup;
    private javax.swing.JPanel panelSupDer;
    private javax.swing.JPanel panelSupIzq;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables
}
