/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import persistencia.Logueador;

/**
 *
 * @author Sebastian
 */
public class AlertWin extends javax.swing.JFrame implements Runnable{
    private Thread threadAlertWin;
    /**
     * Creates new form Splash
     */
    public AlertWin() {        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAlerta = new javax.swing.JPanel();
        panelContenidoAlerta = new org.jdesktop.swingx.JXPanel();
        panelDatosAlerta = new org.jdesktop.swingx.JXPanel();
        panelTitulo = new org.jdesktop.swingx.JXPanel();
        lblTituloAlerta = new org.jdesktop.swingx.JXLabel();
        panelDescripcion = new org.jdesktop.swingx.JXPanel();
        lblDescripcionAlerta = new org.jdesktop.swingx.JXLabel();
        lblIcono = new org.jdesktop.swingx.JXLabel();
        panelNavegacionAlertas = new org.jdesktop.swingx.JXPanel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        barraTimeout = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 550));
        setUndecorated(true);

        panelAlerta.setPreferredSize(new java.awt.Dimension(300, 500));
        panelAlerta.setLayout(new java.awt.BorderLayout());

        panelContenidoAlerta.setPreferredSize(new java.awt.Dimension(300, 486));
        panelContenidoAlerta.setLayout(new java.awt.BorderLayout());

        panelDatosAlerta.setPreferredSize(new java.awt.Dimension(300, 453));
        panelDatosAlerta.setLayout(new java.awt.BorderLayout());

        panelTitulo.setPreferredSize(new java.awt.Dimension(300, 50));

        lblTituloAlerta.setText("Titulo de la alerta...");
        panelTitulo.add(lblTituloAlerta);

        panelDatosAlerta.add(panelTitulo, java.awt.BorderLayout.NORTH);

        panelDescripcion.setPreferredSize(new java.awt.Dimension(300, 400));
        panelDescripcion.setLayout(new java.awt.GridLayout());

        lblDescripcionAlerta.setText("Descripcion alerta");
        panelDescripcion.add(lblDescripcionAlerta);

        lblIcono.setText("jXLabel3");
        panelDescripcion.add(lblIcono);

        panelDatosAlerta.add(panelDescripcion, java.awt.BorderLayout.CENTER);

        panelContenidoAlerta.add(panelDatosAlerta, java.awt.BorderLayout.NORTH);

        btnAnterior.setText("Anterior");
        panelNavegacionAlertas.add(btnAnterior);

        btnSiguiente.setText("Siguiente");
        panelNavegacionAlertas.add(btnSiguiente);

        btnCerrar.setText("Cerrar");
        panelNavegacionAlertas.add(btnCerrar);

        panelContenidoAlerta.add(panelNavegacionAlertas, java.awt.BorderLayout.SOUTH);

        panelAlerta.add(panelContenidoAlerta, java.awt.BorderLayout.CENTER);
        panelAlerta.add(barraTimeout, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelAlerta, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraTimeout;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnSiguiente;
    private org.jdesktop.swingx.JXLabel lblDescripcionAlerta;
    private org.jdesktop.swingx.JXLabel lblIcono;
    private org.jdesktop.swingx.JXLabel lblTituloAlerta;
    private javax.swing.JPanel panelAlerta;
    private org.jdesktop.swingx.JXPanel panelContenidoAlerta;
    private org.jdesktop.swingx.JXPanel panelDatosAlerta;
    private org.jdesktop.swingx.JXPanel panelDescripcion;
    private org.jdesktop.swingx.JXPanel panelNavegacionAlertas;
    private org.jdesktop.swingx.JXPanel panelTitulo;
    // End of variables declaration//GEN-END:variables


    public void hacePreLoad(){
        for (int i = 1;i<=13;i++){
            barraTimeout.setValue(i*10);
            try {
                Thread.sleep(300); 
            } catch (InterruptedException ex) {
                Logger.getLogger(AlertWin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void inicializador() {
        VentanaIbape.getInstance();        
        initComponents();
        this.setVisible(true);
        panelAlerta.setOpaque(false);
        //panelLogo.setForeground(null);
        barraTimeout.setBorderPainted(true);
        barraTimeout.setForeground(new Color(50,50,153,100));
        barraTimeout.setStringPainted(true);
        //this.setSize(500, 500); 
        int posicionX = (Toolkit.getDefaultToolkit().getScreenSize().width/2)-(getWidth()/2);
        int posicionY = Toolkit.getDefaultToolkit().getScreenSize().height/2-(getHeight()/2);
        this.setLocation(posicionX,posicionY);                
        hacePreLoad();        
        setVisible(false);
        dispose();
        VentanaIbape.getInstance().setVisible(true);
    }
    
    public void run(){ 
        inicializador();
        threadAlertWin = null; 
    }
    
    public void start(){
       if (threadAlertWin == null) {
            threadAlertWin = new Thread(this);
            threadAlertWin.setPriority(Thread.MIN_PRIORITY);
            threadAlertWin.start();
        }
    }
    
    
 /*
    public static void main(String args[]) {       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash();
            }
        });
    }
*/

    
    public static void main(String args[]) {
        new AlertWin().run();
    }
    
}
