/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelAyuda.java
 *
 * Created on 26/04/2012, 01:50:48
 */
package gui;

/**
 *
 * @author Sebastian
 */
public class PanelAyuda extends javax.swing.JPanel {
    static PanelAyuda unicaInstancia;
    /** Creates new form PanelAyuda */
    private PanelAyuda() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new org.jdesktop.swingx.JXPanel();
        lblTitulo = new org.jdesktop.swingx.JXLabel();
        panerMedio = new org.jdesktop.swingx.JXPanel();
        panelInferior = new org.jdesktop.swingx.JXPanel();

        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.BorderLayout());

        panelSuperior.setPreferredSize(new java.awt.Dimension(500, 40));

        lblTitulo.setText("Ayuda");
        lblTitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelSuperior.add(lblTitulo);

        add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout panerMedioLayout = new javax.swing.GroupLayout(panerMedio);
        panerMedio.setLayout(panerMedioLayout);
        panerMedioLayout.setHorizontalGroup(
            panerMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panerMedioLayout.setVerticalGroup(
            panerMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        add(panerMedio, java.awt.BorderLayout.CENTER);

        panelInferior.setPreferredSize(new java.awt.Dimension(500, 40));

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        add(panelInferior, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel lblTitulo;
    private org.jdesktop.swingx.JXPanel panelInferior;
    private org.jdesktop.swingx.JXPanel panelSuperior;
    private org.jdesktop.swingx.JXPanel panerMedio;
    // End of variables declaration//GEN-END:variables

    public static PanelAyuda getInstance() {
       if (unicaInstancia == null) {
          unicaInstancia = new PanelAyuda();          
       }
       return unicaInstancia;
    }

}