/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelFinalizarLance.java
 *
 * Created on 23/04/2012, 02:31:19
 */
package gui;

import controllers.ControllerLance;
import controllers.ControllerPpal;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.dataManager.Cajon;
import modelo.dataManager.CategoriaPoi;
import modelo.dataManager.Especie;
import persistencia.BrokerCajon;
import persistencia.BrokerCategoriasPOI;
import persistencia.BrokerEspecie;
import persistencia.BrokerLance;
import persistencia.Logueador;

/**
 *
 * @author Sebastian
 */
public class PanelFinalizarLance extends javax.swing.JPanel {

    static PanelFinalizarLance unicaInstancia;
    private boolean modificandoCajon;
    private Cajon tempCajon;
    private DefaultTableModel modeloTablaCajones = new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{
                "idLance", "# Cajones", "Especie"//, "Acciones"
            }) {

        Class[] types = new Class[]{
            java.lang.Object.class, java.lang.Object.class, java.lang.Object.class//, java.lang.Boolean.class
        };

        @Override
        public Class getColumnClass(int columnIndex) {
            return types[columnIndex];
        }
    };

    /** Creates new form PanelFinalizarLance */
    private PanelFinalizarLance() {
        initComponents();
        inicializador();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new org.jdesktop.swingx.JXPanel();
        lblTitulo = new org.jdesktop.swingx.JXLabel();
        panelMedio = new org.jdesktop.swingx.JXPanel();
        panelCajones = new org.jdesktop.swingx.JXPanel();
        panelTituloTabla = new org.jdesktop.swingx.JXPanel();
        lblTituloTabla = new org.jdesktop.swingx.JXLabel();
        panelTabla = new org.jdesktop.swingx.JXPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCajones = new org.jdesktop.swingx.JXTable();
        panelAccionesCajones = new org.jdesktop.swingx.JXPanel();
        lblAccionesCajones = new org.jdesktop.swingx.JXLabel();
        panelAcciones = new org.jdesktop.swingx.JXPanel();
        btnModificarCajon = new org.jdesktop.swingx.JXHyperlink();
        btnGuardarCajon = new org.jdesktop.swingx.JXHyperlink();
        btnEliminarCajon = new org.jdesktop.swingx.JXHyperlink();
        btnInsertarCajon = new org.jdesktop.swingx.JXHyperlink();
        panelEspecie = new org.jdesktop.swingx.JXPanel();
        panelCantCajones = new org.jdesktop.swingx.JXPanel();
        lblCantCajones = new org.jdesktop.swingx.JXLabel();
        campoCajones = new javax.swing.JTextField();
        panelComboEspecie = new org.jdesktop.swingx.JXPanel();
        lblEspecie = new org.jdesktop.swingx.JXLabel();
        comboEspecies = new javax.swing.JComboBox();
        panelBtnAgregar = new org.jdesktop.swingx.JXPanel();
        jButton1 = new javax.swing.JButton();
        panelSuceso = new org.jdesktop.swingx.JXPanel();
        lblSuceso = new org.jdesktop.swingx.JXLabel();
        comboSuceso = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        panelComentarios = new org.jdesktop.swingx.JXPanel();
        lblComentarios = new org.jdesktop.swingx.JXLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextArea();
        panelInferior = new org.jdesktop.swingx.JXPanel();
        btnGuardarLance = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.BorderLayout());

        panelSuperior.setMaximumSize(new java.awt.Dimension(500, 30));
        panelSuperior.setMinimumSize(new java.awt.Dimension(500, 30));
        panelSuperior.setPreferredSize(new java.awt.Dimension(500, 30));

        lblTitulo.setText("Finalizar lance");
        lblTitulo.setFont(new java.awt.Font("Arial", 0, 18));
        panelSuperior.add(lblTitulo);

        add(panelSuperior, java.awt.BorderLayout.NORTH);

        panelMedio.setMaximumSize(new java.awt.Dimension(500, 420));
        panelMedio.setMinimumSize(new java.awt.Dimension(500, 420));
        panelMedio.setPreferredSize(new java.awt.Dimension(500, 420));
        panelMedio.setLayout(new java.awt.BorderLayout());

        panelCajones.setMaximumSize(new java.awt.Dimension(500, 320));
        panelCajones.setMinimumSize(new java.awt.Dimension(500, 320));
        panelCajones.setPreferredSize(new java.awt.Dimension(500, 320));

        panelTituloTabla.setMaximumSize(new java.awt.Dimension(500, 30));
        panelTituloTabla.setMinimumSize(new java.awt.Dimension(500, 30));
        panelTituloTabla.setPreferredSize(new java.awt.Dimension(500, 30));
        panelTituloTabla.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        lblTituloTabla.setText("Cajones recogidos en el lance:");
        lblTituloTabla.setFont(new java.awt.Font("Tahoma", 0, 12));
        panelTituloTabla.add(lblTituloTabla);

        panelCajones.add(panelTituloTabla);

        panelTabla.setMaximumSize(new java.awt.Dimension(500, 190));
        panelTabla.setMinimumSize(new java.awt.Dimension(500, 190));
        panelTabla.setPreferredSize(new java.awt.Dimension(500, 190));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(500, 170));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(500, 170));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 170));

        tablaCajones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "# Cajones", "Especie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCajones);
        tablaCajones.getColumnModel().getColumn(0).setMinWidth(40);
        tablaCajones.getColumnModel().getColumn(0).setPreferredWidth(40);
        tablaCajones.getColumnModel().getColumn(1).setMinWidth(350);
        tablaCajones.getColumnModel().getColumn(1).setPreferredWidth(350);

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCajones.add(panelTabla);

        panelAccionesCajones.setMaximumSize(new java.awt.Dimension(500, 30));
        panelAccionesCajones.setMinimumSize(new java.awt.Dimension(500, 30));
        panelAccionesCajones.setPreferredSize(new java.awt.Dimension(500, 30));

        lblAccionesCajones.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAccionesCajones.setText("Acciones sobre los cajones elegidos:");
        lblAccionesCajones.setFont(new java.awt.Font("Tahoma", 0, 14));

        panelAcciones.setMaximumSize(new java.awt.Dimension(184, 30));
        panelAcciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        btnModificarCajon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tabla-icono-editar.png"))); // NOI18N
        btnModificarCajon.setText("");
        btnModificarCajon.setToolTipText("Modificar");
        btnModificarCajon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnModificarCajon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCajonActionPerformed(evt);
            }
        });
        panelAcciones.add(btnModificarCajon);

        btnGuardarCajon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tabla-icono-guardar.png"))); // NOI18N
        btnGuardarCajon.setText("");
        btnGuardarCajon.setToolTipText("Guardar cambios");
        btnGuardarCajon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardarCajon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCajonActionPerformed(evt);
            }
        });
        panelAcciones.add(btnGuardarCajon);

        btnEliminarCajon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tabla-icono-eliminar.png"))); // NOI18N
        btnEliminarCajon.setText("");
        btnEliminarCajon.setToolTipText("Eliminar");
        btnEliminarCajon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminarCajon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCajonActionPerformed(evt);
            }
        });
        panelAcciones.add(btnEliminarCajon);

        btnInsertarCajon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tabla-icono-insertar.png"))); // NOI18N
        btnInsertarCajon.setText("");
        btnInsertarCajon.setToolTipText("Agregar");
        btnInsertarCajon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInsertarCajon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarCajonActionPerformed(evt);
            }
        });
        panelAcciones.add(btnInsertarCajon);

        javax.swing.GroupLayout panelAccionesCajonesLayout = new javax.swing.GroupLayout(panelAccionesCajones);
        panelAccionesCajones.setLayout(panelAccionesCajonesLayout);
        panelAccionesCajonesLayout.setHorizontalGroup(
            panelAccionesCajonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionesCajonesLayout.createSequentialGroup()
                .addComponent(lblAccionesCajones, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panelAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelAccionesCajonesLayout.setVerticalGroup(
            panelAccionesCajonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAccionesCajones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelCajones.add(panelAccionesCajones);

        panelEspecie.setMaximumSize(new java.awt.Dimension(500, 50));
        panelEspecie.setMinimumSize(new java.awt.Dimension(500, 50));
        panelEspecie.setPreferredSize(new java.awt.Dimension(500, 50));
        panelEspecie.setLayout(new javax.swing.BoxLayout(panelEspecie, javax.swing.BoxLayout.LINE_AXIS));

        panelCantCajones.setMaximumSize(new java.awt.Dimension(150, 50));
        panelCantCajones.setMinimumSize(new java.awt.Dimension(150, 50));
        panelCantCajones.setPreferredSize(new java.awt.Dimension(150, 50));
        panelCantCajones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        lblCantCajones.setText("Cant. Cajones");
        lblCantCajones.setFont(new java.awt.Font("Tahoma", 0, 12));
        panelCantCajones.add(lblCantCajones);

        campoCajones.setFont(new java.awt.Font("Tahoma", 0, 12));
        campoCajones.setMaximumSize(new java.awt.Dimension(40, 20));
        campoCajones.setMinimumSize(new java.awt.Dimension(40, 20));
        campoCajones.setPreferredSize(new java.awt.Dimension(40, 20));
        panelCantCajones.add(campoCajones);

        panelEspecie.add(panelCantCajones);

        panelComboEspecie.setMaximumSize(new java.awt.Dimension(270, 50));
        panelComboEspecie.setMinimumSize(new java.awt.Dimension(270, 50));
        panelComboEspecie.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        lblEspecie.setText("Especie");
        lblEspecie.setFont(new java.awt.Font("Tahoma", 0, 12));
        panelComboEspecie.add(lblEspecie);

        comboEspecies.setFont(new java.awt.Font("Tahoma", 0, 12));
        comboEspecies.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Abadejo", "Anchoita", "Merluza", "Calamar" }));
        comboEspecies.setMaximumSize(new java.awt.Dimension(200, 20));
        comboEspecies.setMinimumSize(new java.awt.Dimension(200, 20));
        comboEspecies.setPreferredSize(new java.awt.Dimension(200, 20));
        comboEspecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEspeciesActionPerformed(evt);
            }
        });
        panelComboEspecie.add(comboEspecies);

        panelEspecie.add(panelComboEspecie);

        panelBtnAgregar.setMaximumSize(new java.awt.Dimension(80, 50));
        panelBtnAgregar.setMinimumSize(new java.awt.Dimension(80, 50));
        panelBtnAgregar.setPreferredSize(new java.awt.Dimension(80, 50));
        panelBtnAgregar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelBtnAgregar.add(jButton1);

        panelEspecie.add(panelBtnAgregar);

        panelCajones.add(panelEspecie);

        panelMedio.add(panelCajones, java.awt.BorderLayout.NORTH);

        panelSuceso.setMaximumSize(new java.awt.Dimension(500, 50));
        panelSuceso.setMinimumSize(new java.awt.Dimension(500, 50));
        panelSuceso.setPreferredSize(new java.awt.Dimension(500, 50));

        lblSuceso.setText("Suceso ocurrido");
        lblSuceso.setFont(new java.awt.Font("Tahoma", 0, 12));
        panelSuceso.add(lblSuceso);

        comboSuceso.setFont(new java.awt.Font("Tahoma", 0, 12));
        comboSuceso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lista categorias POI" }));
        comboSuceso.setMaximumSize(new java.awt.Dimension(200, 20));
        comboSuceso.setMinimumSize(new java.awt.Dimension(200, 20));
        comboSuceso.setPreferredSize(new java.awt.Dimension(200, 20));
        panelSuceso.add(comboSuceso);

        jButton2.setText("accion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelSuceso.add(jButton2);

        panelMedio.add(panelSuceso, java.awt.BorderLayout.CENTER);

        panelComentarios.setMaximumSize(new java.awt.Dimension(500, 120));
        panelComentarios.setMinimumSize(new java.awt.Dimension(500, 120));
        panelComentarios.setPreferredSize(new java.awt.Dimension(500, 120));
        panelComentarios.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        lblComentarios.setText("Comentarios del lance:");
        lblComentarios.setFont(new java.awt.Font("Tahoma", 0, 12));
        panelComentarios.add(lblComentarios);

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(500, 70));

        txtComentarios.setColumns(20);
        txtComentarios.setFont(new java.awt.Font("Arial", 0, 13));
        txtComentarios.setRows(5);
        jScrollPane2.setViewportView(txtComentarios);

        panelComentarios.add(jScrollPane2);

        panelMedio.add(panelComentarios, java.awt.BorderLayout.SOUTH);

        add(panelMedio, java.awt.BorderLayout.CENTER);

        panelInferior.setMaximumSize(new java.awt.Dimension(500, 50));
        panelInferior.setMinimumSize(new java.awt.Dimension(500, 50));
        panelInferior.setPreferredSize(new java.awt.Dimension(500, 50));
        panelInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        btnGuardarLance.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnGuardarLance.setText("Guardar lance");
        btnGuardarLance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLanceActionPerformed(evt);
            }
        });
        panelInferior.add(btnGuardarLance);

        add(panelInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void comboEspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEspeciesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEspeciesActionPerformed

    private void btnGuardarLanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLanceActionPerformed
        // TODO add your handling code here:
        controllers.ControllerLance.getInstance().guardaLance();

    }//GEN-LAST:event_btnGuardarLanceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!campoCajones.getText().isEmpty() && Integer.valueOf(campoCajones.getText()) > 0 && comboEspecies.getSelectedIndex() > -1) {
            Cajon unCajon = new Cajon();
            unCajon.setIdLance(/*BrokerLance.getInstance().getIdLanceActual()*/1);
            Especie unaEsp = (Especie) comboEspecies.getSelectedItem();
            unCajon.setIdEspecie(unaEsp.getId());
            unCajon.setCantidad(Integer.valueOf(campoCajones.getText()));
            ControllerLance.getInstance().addCajon(unCajon); //quedan en una lista

            cargaGrillaCajones();
            //    int cantCols = 4;
            //    ArrayList a = new ArrayList();
            //    a.add(unCajon.getIdLance());
            //    a.add(unCajon.getCantidad());
            //    a.add(unaEsp.getNombre()/*unCajon.getIdEspecie()*/);
            //    a.add("false");
            //    //insertar la fila 
            //    modeloTablaCajones.addRow(ControllerPpal.getInstance().creaUnaFilaGenerica(cantCols, a));
            //    a.clear();
            //    tablaCajones.setModel(modeloTablaCajones);
            //    ControllerPpal.getInstance().ocultarColJTable(tablaCajones, 0);
        } else {
            JOptionPane.showMessageDialog(null, "No se selecciono una especie o cantidad");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        eliminarCajon();
        //modificarCajon();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnModificarCajonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCajonActionPerformed
        habilitaPanelDatosCajones(true);
        setModificandoCajon(true);
        btnEliminarCajon.setEnabled(false);
        btnInsertarCajon.setEnabled(false);
        btnModificarCajon.setEnabled(false);
        btnGuardarCajon.setEnabled(true);
        //cargo la fila seleccionada en el formulario
        if (tablaCajones.getSelectedRowCount() != 0) {
            Cajon unCajon = (Cajon) tablaCajones.getValueAt(tablaCajones.getSelectedRow(), 0);
            campoCajones.setText(String.valueOf(unCajon.getCantidad()));
            //ver el icono
            setTempCajon(unCajon);
        } else {
            habilitaPanelDatosCajones(false);
            setModificandoCajon(false);
            JOptionPane.showMessageDialog(null, "Seleccione un cajon primero");
        }
    }//GEN-LAST:event_btnModificarCajonActionPerformed

    private void btnGuardarCajonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCajonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCajonActionPerformed

    private void btnEliminarCajonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCajonActionPerformed
        if (tablaCajones.getSelectedRowCount() != 0) {
            int[] listaCajonesSeleccionados = tablaCajones.getSelectedRows();
            if (JOptionPane.showConfirmDialog(null,
                    "Desea eliminar " + listaCajonesSeleccionados.length + " cajones seleccionados?",
                    "Eliminar cajones",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE) == 0) {
                int i = 0;
                while (i < listaCajonesSeleccionados.length) {
                    Cajon unCajon = (Cajon) tablaCajones.getValueAt(i, 0);
                    ControllerLance.getInstance().borrarCajon(unCajon); //lo saca de la lista en memoria
                    System.out.println("Se saco de la lista el cajon " + unCajon);
                    //ControllerLance.getInstance().eliminaCajon(unCajon);
                    i++;
                }
                cargaGrillaCajones();
            }
        }
    }//GEN-LAST:event_btnEliminarCajonActionPerformed

    private void btnInsertarCajonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarCajonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarCajonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXHyperlink btnEliminarCajon;
    private org.jdesktop.swingx.JXHyperlink btnGuardarCajon;
    private javax.swing.JButton btnGuardarLance;
    private org.jdesktop.swingx.JXHyperlink btnInsertarCajon;
    private org.jdesktop.swingx.JXHyperlink btnModificarCajon;
    private javax.swing.JTextField campoCajones;
    private javax.swing.JComboBox comboEspecies;
    private javax.swing.JComboBox comboSuceso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXLabel lblAccionesCajones;
    private org.jdesktop.swingx.JXLabel lblCantCajones;
    private org.jdesktop.swingx.JXLabel lblComentarios;
    private org.jdesktop.swingx.JXLabel lblEspecie;
    private org.jdesktop.swingx.JXLabel lblSuceso;
    private org.jdesktop.swingx.JXLabel lblTitulo;
    private org.jdesktop.swingx.JXLabel lblTituloTabla;
    private org.jdesktop.swingx.JXPanel panelAcciones;
    private org.jdesktop.swingx.JXPanel panelAccionesCajones;
    private org.jdesktop.swingx.JXPanel panelBtnAgregar;
    private org.jdesktop.swingx.JXPanel panelCajones;
    private org.jdesktop.swingx.JXPanel panelCantCajones;
    private org.jdesktop.swingx.JXPanel panelComboEspecie;
    private org.jdesktop.swingx.JXPanel panelComentarios;
    private org.jdesktop.swingx.JXPanel panelEspecie;
    private org.jdesktop.swingx.JXPanel panelInferior;
    private org.jdesktop.swingx.JXPanel panelMedio;
    private org.jdesktop.swingx.JXPanel panelSuceso;
    private org.jdesktop.swingx.JXPanel panelSuperior;
    private org.jdesktop.swingx.JXPanel panelTabla;
    private org.jdesktop.swingx.JXPanel panelTituloTabla;
    private org.jdesktop.swingx.JXTable tablaCajones;
    private javax.swing.JTextArea txtComentarios;
    // End of variables declaration//GEN-END:variables

    public static PanelFinalizarLance getInstance() {
        if (unicaInstancia == null) {
            unicaInstancia = new PanelFinalizarLance();
        }
        return unicaInstancia;
    }

    //main de prueba 
    public static void main(String[] args) {
        javax.swing.JFrame elFrame = new javax.swing.JFrame();
        elFrame.setSize(500, 500);
        PanelFinalizarLance a = new PanelFinalizarLance();
        //cargaEspecies();
        elFrame.add(a);
        elFrame.setVisible(true);
    }

    private void inicializador() {
        cargaComboEspecies();
        cargaComboSuceso();
        // habilitaPanelDatosCajones(false);
    }

    private void cargaComboEspecies() {
        try {
            comboEspecies.removeAllItems();
            for (Especie i : controllers.ControllerLance.getInstance().getListadoEspecies()) {
                comboEspecies.addItem(i);
            }
        } catch (Exception e) {
            Logueador.getInstance().agregaAlLog(e.toString());
        }
    }

    /*public ArrayList<Cajon> getCajones() {
    //------------
    for (int i = 0; i < tablaCajones.getRowCount(); i++) {
    }
    
    //------------
    ArrayList<Cajon> listaCajones = null;
    Cajon unCajon = new Cajon();
    for (int i = 0; i < tablaCajones.getRowCount(); i++) {
    unCajon.setIdLance(0); //que lance?
    //  unCajon.setIdEspecie(tablaCajones.getModel().getValueAt(i, 0));
    //  unCajon.setCantidad(tablaCajones.getModel().getValueAt(i, 1));
    listaCajones.add(unCajon);
    }
    return listaCajones;
    }*/
    public String getComentarios() {
        if (!txtComentarios.getText().isEmpty()) {
            return txtComentarios.getText();
        } else {
            return "";
        }
    }

    private void cargaComboSuceso() {
        try {
            comboSuceso.removeAllItems();
            for (CategoriaPoi i : BrokerCategoriasPOI.getInstance().getCatPOISFromDB()) {
                comboSuceso.addItem(i);
            }
        } catch (Exception e) {
            Logueador.getInstance().agregaAlLog(e.toString());
        }
    }

    private void eliminarCajon() {
        /* if (JOptionPane.showConfirmDialog(null,
        "Desea eliminar los cajones seleccionados?",
        "Eliminar cajones",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE) == 0) {
        for (int i = 0; i < tablaCajones.getRowCount(); i++) {
        if ((Boolean) tablaCajones.getValueAt(i, tablaCajones.getColumnCount(false) - 1)) {
        ControllerLance.getInstance().borrarCajon((Cajon) tablaCajones.getValueAt(i, 0));
        }
        }
        }
        cargaGrillaCajones();*/
    }

    private void modificarCajon() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    private void cargaGrillaCajones() {
        int cantCols = 4;
        ArrayList a = new ArrayList();
        modeloTablaCajones.setRowCount(0);//vacia la tabla
        //ControllerPpal.getInstance().vaciarJTable(modeloTablaCajones);//da exeption
        ArrayList<Cajon> b = ControllerLance.getInstance().getListadoCajones();

        for (Cajon unCajon : ControllerLance.getInstance().getListadoCajones()) {
            modeloTablaCajones.addRow(new Object[]{
                        unCajon,//<--Aca esta el objeto -muestra idLance
                        unCajon.getCantidad(),
                        BrokerEspecie.getInstance().getEspecieFromDB(unCajon.getIdEspecie()).getNombre()
                    });
        }

/*
        for (int i = 0; i < b.size(); i++) {
            a.add(b.get(i));//<--Aca esta el objeto -muestra idLance
            a.add(b.get(i).getCantidad());
            a.add(BrokerEspecie.getInstance().getEspecieFromDB(b.get(i).getIdEspecie()).getNombre());//unCajon.getIdEspecie());
            a.add("false");
            //insertar la fila 
            modeloTablaCajones.addRow(ControllerPpal.getInstance().creaUnaFilaGenerica(cantCols, a));
            a.clear();

        }*/
        tablaCajones.setModel(modeloTablaCajones);
        ControllerPpal.getInstance().ocultarColJTable(tablaCajones, 0);
    }

    private void habilitaPanelDatosCajones(boolean estado) {
        campoCajones.setEnabled(estado);
        campoCajones.setText("");
        //si lo deshabilito habilito la barra
        if (!estado) {
            btnEliminarCajon.setEnabled(!estado);
            btnInsertarCajon.setEnabled(!estado);
            btnModificarCajon.setEnabled(!estado);
            btnGuardarCajon.setEnabled(estado);
        }
    }

    /**
     * @return the modificandoCajon
     */
    public boolean isModificandoCajon() {
        return modificandoCajon;
    }

    /**
     * @param modificandoCajon the modificandoCajon to set
     */
    public void setModificandoCajon(boolean modificandoCajon) {
        this.modificandoCajon = modificandoCajon;
    }

    /**
     * @return the tempCajon
     */
    public Cajon getTempCajon() {
        return tempCajon;
    }

    /**
     * @param tempCajon the tempCajon to set
     */
    public void setTempCajon(Cajon tempCajon) {
        this.tempCajon = tempCajon;
    }
}