/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelOpcPOIs.java
 *
 * Created on 19/04/2012, 01:46:19
 */
package gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.dataManager.CategoriaPoi;
import modelo.dataManager.POI;
import persistencia.BrokerCategoriasPOI;
import persistencia.BrokerPOIs;
import persistencia.BrokerPpal;

/**
 *
 * @author Sebastian
 */
public class PanelOpcPOIs extends javax.swing.JPanel {

    static PanelOpcPOIs unicaInstancia;
    private DefaultTableModel modeloTablaPOIS = new DefaultTableModel();
    private DefaultTableModel modeloTablaCategoriasPOI = new DefaultTableModel();

    ;

    /** Creates new form PanelOpcPOIs */
    private PanelOpcPOIs() {
        initComponents();
        inicializador();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        panelTodo = new org.jdesktop.swingx.JXPanel();
        panelTitulo = new org.jdesktop.swingx.JXPanel();
        lblTitulo = new org.jdesktop.swingx.JXLabel();
        panelPois = new org.jdesktop.swingx.JXPanel();
        panelPoisTitulo = new org.jdesktop.swingx.JXPanel();
        lblTituloTablaPois = new org.jdesktop.swingx.JXLabel();
        panelTablaPois = new org.jdesktop.swingx.JXPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPois = new org.jdesktop.swingx.JXTable();
        panelAgregaPoi = new org.jdesktop.swingx.JXPanel();
        panelCatNuevoPoi = new org.jdesktop.swingx.JXPanel();
        lblCategoria = new org.jdesktop.swingx.JXLabel();
        comboCategorias = new javax.swing.JComboBox();
        panelDescripNuevoPoi = new org.jdesktop.swingx.JXPanel();
        lblDescripciónNuevoPoi = new org.jdesktop.swingx.JXLabel();
        campoDescripcionNuevoPoi = new javax.swing.JTextField();
        panelBtnAgregaPoi = new org.jdesktop.swingx.JXPanel();
        btnAgregaPoi = new javax.swing.JButton();
        panelCategoriaPois = new org.jdesktop.swingx.JXPanel();
        panelCatTitulo = new org.jdesktop.swingx.JXPanel();
        lblTituloTablaCategorias = new org.jdesktop.swingx.JXLabel();
        panelTablaCategorias = new org.jdesktop.swingx.JXPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCategorias = new org.jdesktop.swingx.JXTable();
        panelAgregaCategoria = new org.jdesktop.swingx.JXPanel();
        panelNombreNuevaCat = new org.jdesktop.swingx.JXPanel();
        lblNombreNuevaCat = new org.jdesktop.swingx.JXLabel();
        campoNombreNuevaCat = new javax.swing.JTextField();
        panelBtnAgregaCategoria = new org.jdesktop.swingx.JXPanel();
        btnAgregaCategoria = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(520, 500));
        setLayout(new java.awt.BorderLayout());

        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(520, 500));

        panelTodo.setMinimumSize(new java.awt.Dimension(400, 360));
        panelTodo.setPreferredSize(new java.awt.Dimension(500, 670));
        panelTodo.setScrollableTracksViewportHeight(false);
        panelTodo.setScrollableTracksViewportWidth(false);

        panelTitulo.setMaximumSize(new java.awt.Dimension(500, 40));
        panelTitulo.setMinimumSize(new java.awt.Dimension(500, 40));
        panelTitulo.setPreferredSize(new java.awt.Dimension(500, 40));

        lblTitulo.setText("Administración de Puntos de Interes (POI)");
        lblTitulo.setFont(new java.awt.Font("Arial", 0, 18));
        panelTitulo.add(lblTitulo);

        panelTodo.add(panelTitulo);

        panelPois.setMaximumSize(new java.awt.Dimension(500, 350));
        panelPois.setMinimumSize(new java.awt.Dimension(500, 350));
        panelPois.setPreferredSize(new java.awt.Dimension(500, 350));
        panelPois.setLayout(new java.awt.BorderLayout());

        panelPoisTitulo.setMaximumSize(new java.awt.Dimension(500, 30));
        panelPoisTitulo.setMinimumSize(new java.awt.Dimension(500, 30));
        panelPoisTitulo.setPreferredSize(new java.awt.Dimension(500, 30));
        panelPoisTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTituloTablaPois.setText("Listado de POIs:");
        lblTituloTablaPois.setFont(new java.awt.Font("Tahoma", 0, 14));
        panelPoisTitulo.add(lblTituloTablaPois);

        panelPois.add(panelPoisTitulo, java.awt.BorderLayout.NORTH);

        panelTablaPois.setMaximumSize(new java.awt.Dimension(500, 300));
        panelTablaPois.setMinimumSize(new java.awt.Dimension(500, 300));
        panelTablaPois.setPreferredSize(new java.awt.Dimension(500, 300));
        panelTablaPois.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(500, 300));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(500, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 300));

        tablaPois.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha y Hora", "Categoria", "Coordenadas", "Descripcion", "Acciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPois);
        tablaPois.getColumnModel().getColumn(0).setMinWidth(70);
        tablaPois.getColumnModel().getColumn(0).setPreferredWidth(70);
        tablaPois.getColumnModel().getColumn(4).setMinWidth(60);
        tablaPois.getColumnModel().getColumn(4).setPreferredWidth(60);
        tablaPois.getColumnModel().getColumn(4).setMaxWidth(60);

        panelTablaPois.add(jScrollPane1);

        panelPois.add(panelTablaPois, java.awt.BorderLayout.CENTER);

        panelAgregaPoi.setMaximumSize(new java.awt.Dimension(500, 50));
        panelAgregaPoi.setMinimumSize(new java.awt.Dimension(500, 50));
        panelAgregaPoi.setPreferredSize(new java.awt.Dimension(500, 50));
        panelAgregaPoi.setLayout(new java.awt.BorderLayout());

        panelCatNuevoPoi.setMaximumSize(new java.awt.Dimension(200, 500));
        panelCatNuevoPoi.setMinimumSize(new java.awt.Dimension(200, 500));
        panelCatNuevoPoi.setPreferredSize(new java.awt.Dimension(200, 500));
        panelCatNuevoPoi.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        lblCategoria.setText("Categoria");
        lblCategoria.setFont(new java.awt.Font("Tahoma", 0, 12));
        panelCatNuevoPoi.add(lblCategoria);

        comboCategorias.setFont(new java.awt.Font("Tahoma", 0, 12));
        comboCategorias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Red rota", "Buen Abadejo", "Fondo rocoso" }));
        comboCategorias.setMaximumSize(new java.awt.Dimension(130, 20));
        comboCategorias.setMinimumSize(new java.awt.Dimension(130, 20));
        comboCategorias.setPreferredSize(new java.awt.Dimension(130, 20));
        comboCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriasActionPerformed(evt);
            }
        });
        panelCatNuevoPoi.add(comboCategorias);

        panelAgregaPoi.add(panelCatNuevoPoi, java.awt.BorderLayout.WEST);

        panelDescripNuevoPoi.setMaximumSize(new java.awt.Dimension(250, 500));
        panelDescripNuevoPoi.setMinimumSize(new java.awt.Dimension(250, 500));
        panelDescripNuevoPoi.setPreferredSize(new java.awt.Dimension(250, 500));
        panelDescripNuevoPoi.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        lblDescripciónNuevoPoi.setText("Descripción");
        lblDescripciónNuevoPoi.setFont(new java.awt.Font("Tahoma", 0, 12));
        panelDescripNuevoPoi.add(lblDescripciónNuevoPoi);

        campoDescripcionNuevoPoi.setMaximumSize(new java.awt.Dimension(140, 20));
        campoDescripcionNuevoPoi.setMinimumSize(new java.awt.Dimension(140, 20));
        campoDescripcionNuevoPoi.setPreferredSize(new java.awt.Dimension(140, 20));
        panelDescripNuevoPoi.add(campoDescripcionNuevoPoi);

        panelAgregaPoi.add(panelDescripNuevoPoi, java.awt.BorderLayout.CENTER);

        panelBtnAgregaPoi.setMaximumSize(new java.awt.Dimension(80, 500));
        panelBtnAgregaPoi.setMinimumSize(new java.awt.Dimension(80, 500));
        panelBtnAgregaPoi.setPreferredSize(new java.awt.Dimension(80, 500));
        panelBtnAgregaPoi.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 13));

        btnAgregaPoi.setText("Agrega POI");
        btnAgregaPoi.setAutoscrolls(true);
        btnAgregaPoi.setMargin(new java.awt.Insets(2, 1, 2, 1));
        btnAgregaPoi.setMaximumSize(new java.awt.Dimension(70, 23));
        btnAgregaPoi.setMinimumSize(new java.awt.Dimension(70, 23));
        btnAgregaPoi.setPreferredSize(new java.awt.Dimension(70, 23));
        btnAgregaPoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaPoiActionPerformed(evt);
            }
        });
        panelBtnAgregaPoi.add(btnAgregaPoi);

        panelAgregaPoi.add(panelBtnAgregaPoi, java.awt.BorderLayout.EAST);

        panelPois.add(panelAgregaPoi, java.awt.BorderLayout.SOUTH);

        panelTodo.add(panelPois);

        panelCategoriaPois.setMaximumSize(new java.awt.Dimension(500, 280));
        panelCategoriaPois.setMinimumSize(new java.awt.Dimension(500, 250));
        panelCategoriaPois.setPreferredSize(new java.awt.Dimension(500, 280));
        panelCategoriaPois.setScrollableTracksViewportHeight(false);
        panelCategoriaPois.setScrollableTracksViewportWidth(false);
        panelCategoriaPois.setLayout(new java.awt.BorderLayout());

        panelCatTitulo.setMaximumSize(new java.awt.Dimension(500, 30));
        panelCatTitulo.setMinimumSize(new java.awt.Dimension(500, 30));
        panelCatTitulo.setPreferredSize(new java.awt.Dimension(500, 30));
        panelCatTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTituloTablaCategorias.setText("Categorías de POIs:");
        lblTituloTablaCategorias.setFont(new java.awt.Font("Tahoma", 0, 14));
        panelCatTitulo.add(lblTituloTablaCategorias);

        panelCategoriaPois.add(panelCatTitulo, java.awt.BorderLayout.NORTH);

        panelTablaCategorias.setMaximumSize(new java.awt.Dimension(500, 200));
        panelTablaCategorias.setMinimumSize(new java.awt.Dimension(500, 200));
        panelTablaCategorias.setPreferredSize(new java.awt.Dimension(500, 200));
        panelTablaCategorias.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jScrollPane2.setMaximumSize(new java.awt.Dimension(500, 200));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(500, 200));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(500, 200));

        tablaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre de Categoria", "Icono", "Acciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaCategorias);
        tablaCategorias.getColumnModel().getColumn(1).setMinWidth(50);
        tablaCategorias.getColumnModel().getColumn(1).setPreferredWidth(50);
        tablaCategorias.getColumnModel().getColumn(1).setMaxWidth(50);
        tablaCategorias.getColumnModel().getColumn(2).setMinWidth(100);
        tablaCategorias.getColumnModel().getColumn(2).setPreferredWidth(100);
        tablaCategorias.getColumnModel().getColumn(2).setMaxWidth(50);

        panelTablaCategorias.add(jScrollPane2);

        panelCategoriaPois.add(panelTablaCategorias, java.awt.BorderLayout.CENTER);

        panelAgregaCategoria.setMaximumSize(new java.awt.Dimension(500, 50));
        panelAgregaCategoria.setMinimumSize(new java.awt.Dimension(500, 50));
        panelAgregaCategoria.setPreferredSize(new java.awt.Dimension(500, 50));
        panelAgregaCategoria.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        panelNombreNuevaCat.setMaximumSize(new java.awt.Dimension(300, 500));
        panelNombreNuevaCat.setMinimumSize(new java.awt.Dimension(300, 500));
        panelNombreNuevaCat.setPreferredSize(new java.awt.Dimension(300, 500));
        panelNombreNuevaCat.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        lblNombreNuevaCat.setText("Nombre");
        lblNombreNuevaCat.setFont(new java.awt.Font("Tahoma", 0, 12));
        panelNombreNuevaCat.add(lblNombreNuevaCat);

        campoNombreNuevaCat.setMaximumSize(new java.awt.Dimension(170, 20));
        campoNombreNuevaCat.setMinimumSize(new java.awt.Dimension(170, 20));
        campoNombreNuevaCat.setPreferredSize(new java.awt.Dimension(170, 20));
        panelNombreNuevaCat.add(campoNombreNuevaCat);

        panelAgregaCategoria.add(panelNombreNuevaCat);

        panelBtnAgregaCategoria.setMaximumSize(new java.awt.Dimension(150, 500));
        panelBtnAgregaCategoria.setMinimumSize(new java.awt.Dimension(150, 500));
        panelBtnAgregaCategoria.setPreferredSize(new java.awt.Dimension(150, 500));
        panelBtnAgregaCategoria.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 9));

        btnAgregaCategoria.setText("Agrega Categoria");
        btnAgregaCategoria.setAutoscrolls(true);
        btnAgregaCategoria.setMargin(new java.awt.Insets(2, 1, 2, 1));
        btnAgregaCategoria.setMaximumSize(new java.awt.Dimension(120, 23));
        btnAgregaCategoria.setMinimumSize(new java.awt.Dimension(120, 23));
        btnAgregaCategoria.setPreferredSize(new java.awt.Dimension(120, 23));
        btnAgregaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaCategoriaActionPerformed(evt);
            }
        });
        panelBtnAgregaCategoria.add(btnAgregaCategoria);

        panelAgregaCategoria.add(panelBtnAgregaCategoria);

        panelCategoriaPois.add(panelAgregaCategoria, java.awt.BorderLayout.SOUTH);

        panelTodo.add(panelCategoriaPois);

        jScrollPane3.setViewportView(panelTodo);

        add(jScrollPane3, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void comboCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoriasActionPerformed

    private void btnAgregaPoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaPoiActionPerformed
        // Agrega POI:        
        if (comboCategorias.getItemCount() > 0 && campoDescripcionNuevoPoi.getText().length() > 3) {
            CategoriaPoi cP = (CategoriaPoi) comboCategorias.getSelectedItem();
            controllers.ControllerPois.getInstance().agregaPOI(cP.getId(), campoDescripcionNuevoPoi.getText());
            cargaGrillaPOIS();
        } else {
            JOptionPane.showMessageDialog(null, "No se selecciono una categoria o el nombre no es valido");
        }

    }//GEN-LAST:event_btnAgregaPoiActionPerformed

    private void btnAgregaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaCategoriaActionPerformed
        // Agrega Categoria POI:
        if (campoNombreNuevaCat.getText().length() > 3) {        
        controllers.ControllerPois.getInstance().agregaCategoriaPOI(campoNombreNuevaCat.getText());
        cargaGrillaCategoriaPOIS();
        cargaComboCategorias();
        } else {
            JOptionPane.showMessageDialog(null, "El nombre  de la categoria no es valido");
        }
    }//GEN-LAST:event_btnAgregaCategoriaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregaCategoria;
    private javax.swing.JButton btnAgregaPoi;
    private javax.swing.JTextField campoDescripcionNuevoPoi;
    private javax.swing.JTextField campoNombreNuevaCat;
    private javax.swing.JComboBox comboCategorias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXLabel lblCategoria;
    private org.jdesktop.swingx.JXLabel lblDescripciónNuevoPoi;
    private org.jdesktop.swingx.JXLabel lblNombreNuevaCat;
    private org.jdesktop.swingx.JXLabel lblTitulo;
    private org.jdesktop.swingx.JXLabel lblTituloTablaCategorias;
    private org.jdesktop.swingx.JXLabel lblTituloTablaPois;
    private org.jdesktop.swingx.JXPanel panelAgregaCategoria;
    private org.jdesktop.swingx.JXPanel panelAgregaPoi;
    private org.jdesktop.swingx.JXPanel panelBtnAgregaCategoria;
    private org.jdesktop.swingx.JXPanel panelBtnAgregaPoi;
    private org.jdesktop.swingx.JXPanel panelCatNuevoPoi;
    private org.jdesktop.swingx.JXPanel panelCatTitulo;
    private org.jdesktop.swingx.JXPanel panelCategoriaPois;
    private org.jdesktop.swingx.JXPanel panelDescripNuevoPoi;
    private org.jdesktop.swingx.JXPanel panelNombreNuevaCat;
    private org.jdesktop.swingx.JXPanel panelPois;
    private org.jdesktop.swingx.JXPanel panelPoisTitulo;
    private org.jdesktop.swingx.JXPanel panelTablaCategorias;
    private org.jdesktop.swingx.JXPanel panelTablaPois;
    private org.jdesktop.swingx.JXPanel panelTitulo;
    private org.jdesktop.swingx.JXPanel panelTodo;
    private org.jdesktop.swingx.JXTable tablaCategorias;
    private org.jdesktop.swingx.JXTable tablaPois;
    // End of variables declaration//GEN-END:variables

    public static PanelOpcPOIs getInstance() {
        if (unicaInstancia == null) {
            unicaInstancia = new PanelOpcPOIs();
        }
        return unicaInstancia;
    }

    private void inicializador() {
        try {
            cargaGrillaPOIS();
            cargaGrillaCategoriaPOIS();
            cargaComboCategorias();
            //obtengo ide del selected recuperando el objeto:
            //CategoriaPoi s = (CategoriaPoi) comboCategorias.getSelectedItem();
            //s.getId();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    /*    //main de prueba
    
    public static void main(String[] args) {
    javax.swing.JFrame elFrame = new javax.swing.JFrame();
    elFrame.setSize(500, 500);
    PanelOpcPOIs a = new PanelOpcPOIs();
    //cargaEspecies();
    elFrame.add(a);
    elFrame.setVisible(true);
    }*/

    private void cargaComboCategorias() {
        //carga combo
        comboCategorias.removeAllItems();
        for (CategoriaPoi cP : controllers.ControllerPois.getInstance().cargaCategoriasPOI()) {
            comboCategorias.addItem(cP);
        }
    }

    private void vaciarJTable(DefaultTableModel dTM) {
        dTM.setColumnCount(0);
        while (dTM.getRowCount() > 0) {
            dTM.removeRow(0);
        }
        //dTM.setRowCount(0);
    }

    private void ocultarColJTable(JTable tabla, int indice) {
        tabla.getColumnModel().getColumn(indice).setMaxWidth(0);
        tabla.getColumnModel().getColumn(indice).setMinWidth(0);
        tabla.getColumnModel().getColumn(indice).setPreferredWidth(0);
    }

    private Object[] agregaUnaFilaGenerica(int cantCols, ArrayList unObjeto) {
        //SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Object[] fila = new Object[cantCols]; //creamos la fila
        for (int i = 0; i < unObjeto.size(); i++) {
            if (unObjeto.get(i) != null) {
                fila[i] = String.valueOf(unObjeto.get(i));
            } else {
                fila[i] = "";
            }
        }
        return fila;
    }

    private void cargaGrillaCategoriaPOIS() {
        //DefaultTableModel dm = (DefaultTableModel) tablaCategorias.getModel(); 
        //modeloTablaCategoriasPOI = (DefaultTableModel) tablaCategorias.getModel();
        //tablaCategorias.setModel(modeloTablaCategoriasPOI);
        vaciarJTable(modeloTablaCategoriasPOI);
        //dm.setRowCount(0);
        int cantCols = 4;
        //Cabecera
        /*String[] encabezado = new String[4];
        encabezado[0] = "id";
        encabezado[1] = "Nombre de la categoria";
        encabezado[2] = "Icono";
        encabezado[3] = "Acciones";
        dm.setColumnIdentifiers(encabezado);*/
        modeloTablaCategoriasPOI.addColumn("id");
        modeloTablaCategoriasPOI.addColumn("Nombre de la categoria");
        modeloTablaCategoriasPOI.addColumn("Icono");
        modeloTablaCategoriasPOI.addColumn("Acciones");
        //Cuerpo
        ArrayList a = new ArrayList();
        for (CategoriaPoi cP : BrokerCategoriasPOI.getInstance().getCatPOISFromDB()) {
            a.clear();
            a.add(cP.getId());
            a.add(cP.getTitulo());
            a.add(cP.getPathIcono());
            a.add("Acciones");
            modeloTablaCategoriasPOI.addRow(agregaUnaFilaGenerica(cantCols, a));
        }
        tablaCategorias.setModel(modeloTablaCategoriasPOI);
        //escondo la columna ID 
        tablaCategorias.getColumnModel().getColumn(0).setMinWidth(0);
        tablaCategorias.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaCategorias.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaCategorias.getColumnModel().getColumn(0).setResizable(false);

    }

    private void cargaGrillaPOIS() {
        try {
            //DefaultTableModel dm = (DefaultTableModel) tablaPois.getModel();
            //modeloTablaPOIS = (DefaultTableModel) tablaPois.getModel();
            //tablaPois.setModel(modeloTablaPOIS);
            vaciarJTable(modeloTablaPOIS);
            //dm.setRowCount(0);
            int cantCols = 6;
            //Cabecera
            /*String[] encabezado = new String[6];
            encabezado[0] = "id";
            encabezado[1] = "Fecha y Hora";
            encabezado[2] = "Categoria";
            encabezado[3] = "Coordenadas";
            encabezado[4] = "Descripcion";
            encabezado[5] = "Acciones";
            modeloTablaPOIS.setColumnCount(cantCols-1);
            modeloTablaPOIS.setColumnIdentifiers(encabezado);*/
            // modeloTablaPOIS.setColumnCount(cantCols);
            modeloTablaPOIS.addColumn("id");
            modeloTablaPOIS.addColumn("Fecha y Hora");
            modeloTablaPOIS.addColumn("Categoria");
            modeloTablaPOIS.addColumn("Coordenadas");
            modeloTablaPOIS.addColumn("Descripcion");
            modeloTablaPOIS.addColumn("Acciones");

            //Cuerpo
        /*for (POI p : BrokerPOIs.getInstance().getPOISFromDB()) {
            dm.addRow(agregaUnaFilaPOI(p.getId(), p.getFechaHora(), BrokerCategoriasPOI.getInstance().getCatPOIFromDB(p.getIdCategoriaPOI()).getTitulo(), p.getDescripcion(), p.getLatitud(), p.getLongitud()));
            }*/
            ArrayList a = new ArrayList();
            for (POI p : BrokerPOIs.getInstance().getPOISFromDB()) {
                a.clear();
                a.add(p.getId());
                a.add(p.getFechaHora());
                a.add(BrokerCategoriasPOI.getInstance().getCatPOIFromDB(p.getIdCategoriaPOI()).getTitulo());
                String coordenadas = String.valueOf(p.getLatitud()) + "," + String.valueOf(p.getLongitud());
                a.add(coordenadas);
                a.add(p.getDescripcion());
                a.add("Acciones");
                modeloTablaPOIS.addRow(agregaUnaFilaGenerica(cantCols, a));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        tablaPois.setModel(modeloTablaPOIS);
        //escondo la columna ID 
        tablaPois.getColumnModel().getColumn(0).setMinWidth(0);
        tablaPois.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaPois.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaPois.getColumnModel().getColumn(0).setResizable(false);
    }
}
