/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelOpcCampanias.java
 *
 * Created on 19/04/2012, 15:41:25
 */
package gui;

import java.awt.Color;
import java.util.Date;
import javax.swing.AbstractCellEditor;
import javax.swing.DefaultCellEditor;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import org.jdesktop.swingx.JXHyperlink;
import org.jdesktop.swingx.JXPanel;

/**
 *
 * @author Sebastian
 */
public class PanelOpcCampanias extends javax.swing.JPanel {
    static PanelOpcCampanias unicaInstancia;
    private int estadoCampania=0; //0=no hay campaña, 1=campania en curso, 2=campaña Pausada
    private Color colorOriginalBtnIniciar;
    private DefaultTableModel modeloTabla;
    private int NRO_COL_ID_CAMP=0;
    private int NRO_COL_FECHA_INI=1;
    private int NRO_COL_FECHA_FIN=2;
    private int NRO_COL_DURACION=3;
    private int NRO_COL_NOMBRE_CAMP=4;
    private int NRO_COL_BARCO=5;
    private int NRO_COL_CAPITAN=6;
    private int NRO_COL_ACCIONES=7;
    private int cantColumnas=8;
    
    //</editor-fold>
    /** Creates new form PanelOpcCampanias */
    private PanelOpcCampanias() {
        initComponents();        
        inicializaTabla();
        setGuiCampaniaFinalizada();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new org.jdesktop.swingx.JXPanel();
        lblTituloCampanias = new org.jdesktop.swingx.JXLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelCentro = new org.jdesktop.swingx.JXPanel();
        panelTablaCampanias = new org.jdesktop.swingx.JXPanel();
        panelTituloTabla = new org.jdesktop.swingx.JXPanel();
        lblTituloTabla = new org.jdesktop.swingx.JXLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCampanias = new org.jdesktop.swingx.JXTable();
        panelNuevaCampania = new org.jdesktop.swingx.JXPanel();
        panelTituloNuevaCampania = new org.jdesktop.swingx.JXPanel();
        lblNuevaCampania = new org.jdesktop.swingx.JXLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelDatosNuevaCampania = new org.jdesktop.swingx.JXPanel();
        panelNombreCamp = new org.jdesktop.swingx.JXPanel();
        panelLblNombre = new org.jdesktop.swingx.JXPanel();
        lblNombre = new org.jdesktop.swingx.JXLabel();
        panelCampoNombre = new org.jdesktop.swingx.JXPanel();
        campoNombreCampania = new javax.swing.JTextField();
        panelBarcoCamp = new org.jdesktop.swingx.JXPanel();
        panelLbBarco = new org.jdesktop.swingx.JXPanel();
        lblBarco = new org.jdesktop.swingx.JXLabel();
        panelCampoBarco = new org.jdesktop.swingx.JXPanel();
        campoBarcoCampania = new javax.swing.JTextField();
        panelCapitanCamp = new org.jdesktop.swingx.JXPanel();
        panelLblCapitan = new org.jdesktop.swingx.JXPanel();
        lblCapitan = new org.jdesktop.swingx.JXLabel();
        panelCampoCapitan = new org.jdesktop.swingx.JXPanel();
        campoCapitanCampania = new javax.swing.JTextField();
        panelBtnCampania = new org.jdesktop.swingx.JXPanel();
        btnComenzarCampania = new javax.swing.JButton();
        btnPausarReanudarCampania = new javax.swing.JButton();
        btnFinalizarCampania = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.BorderLayout());

        panelTitulo.setMaximumSize(new java.awt.Dimension(500, 40));
        panelTitulo.setMinimumSize(new java.awt.Dimension(500, 40));
        panelTitulo.setPreferredSize(new java.awt.Dimension(500, 40));
        panelTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        lblTituloCampanias.setText("Campañas");
        lblTituloCampanias.setFont(new java.awt.Font("Arial", 0, 18));
        panelTitulo.add(lblTituloCampanias);

        add(panelTitulo, java.awt.BorderLayout.NORTH);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(480, 410));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(480, 410));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(480, 410));

        panelCentro.setMaximumSize(new java.awt.Dimension(460, 410));
        panelCentro.setMinimumSize(new java.awt.Dimension(460, 410));
        panelCentro.setPreferredSize(new java.awt.Dimension(460, 410));
        panelCentro.setScrollableTracksViewportHeight(false);
        panelCentro.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        panelTablaCampanias.setMaximumSize(new java.awt.Dimension(450, 250));
        panelTablaCampanias.setMinimumSize(new java.awt.Dimension(450, 250));
        panelTablaCampanias.setPreferredSize(new java.awt.Dimension(450, 250));

        panelTituloTabla.setMaximumSize(new java.awt.Dimension(450, 30));
        panelTituloTabla.setMinimumSize(new java.awt.Dimension(450, 30));
        panelTituloTabla.setPreferredSize(new java.awt.Dimension(450, 30));
        panelTituloTabla.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTituloTabla.setText("Listado de campañas en disco:");
        lblTituloTabla.setFont(new java.awt.Font("Tahoma", 0, 14));
        panelTituloTabla.add(lblTituloTabla);

        panelTablaCampanias.add(panelTituloTabla);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(450, 220));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(450, 220));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 220));

        tablaCampanias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Fecha Inicio", "Fecha Fin", "Duración [dias]", "Nombre de Campaña", "Barco", "Capitan", "Acciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCampanias.setPreferredScrollableViewportSize(new java.awt.Dimension(450, 360));
        tablaCampanias.setPreferredSize(new java.awt.Dimension(450, 72));
        tablaCampanias.setRowHeight(30);
        jScrollPane1.setViewportView(tablaCampanias);
        tablaCampanias.getColumnModel().getColumn(0).setMinWidth(0);
        tablaCampanias.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaCampanias.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaCampanias.getColumnModel().getColumn(4).setMinWidth(80);
        tablaCampanias.getColumnModel().getColumn(4).setPreferredWidth(80);
        tablaCampanias.getColumnModel().getColumn(7).setMinWidth(0);
        tablaCampanias.getColumnModel().getColumn(7).setPreferredWidth(0);
        tablaCampanias.getColumnModel().getColumn(7).setMaxWidth(0);

        panelTablaCampanias.add(jScrollPane1);

        panelCentro.add(panelTablaCampanias);

        panelNuevaCampania.setMaximumSize(new java.awt.Dimension(450, 160));
        panelNuevaCampania.setMinimumSize(new java.awt.Dimension(450, 160));
        panelNuevaCampania.setPreferredSize(new java.awt.Dimension(450, 160));
        panelNuevaCampania.setLayout(new java.awt.BorderLayout());

        panelTituloNuevaCampania.setMaximumSize(new java.awt.Dimension(450, 30));
        panelTituloNuevaCampania.setMinimumSize(new java.awt.Dimension(450, 30));
        panelTituloNuevaCampania.setPreferredSize(new java.awt.Dimension(450, 30));
        panelTituloNuevaCampania.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        lblNuevaCampania.setText("Nueva Campaña:");
        lblNuevaCampania.setFont(new java.awt.Font("Tahoma", 0, 14));
        panelTituloNuevaCampania.add(lblNuevaCampania);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelTituloNuevaCampania.add(jButton1);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelTituloNuevaCampania.add(jButton2);

        panelNuevaCampania.add(panelTituloNuevaCampania, java.awt.BorderLayout.NORTH);

        panelDatosNuevaCampania.setMaximumSize(new java.awt.Dimension(450, 130));
        panelDatosNuevaCampania.setMinimumSize(new java.awt.Dimension(450, 130));
        panelDatosNuevaCampania.setPreferredSize(new java.awt.Dimension(450, 130));
        panelDatosNuevaCampania.setLayout(new java.awt.GridLayout(3, 1));

        panelNombreCamp.setMaximumSize(new java.awt.Dimension(450, 43));
        panelNombreCamp.setMinimumSize(new java.awt.Dimension(450, 43));
        panelNombreCamp.setPreferredSize(new java.awt.Dimension(450, 43));
        panelNombreCamp.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        panelLblNombre.setMaximumSize(new java.awt.Dimension(100, 43));
        panelLblNombre.setMinimumSize(new java.awt.Dimension(100, 43));
        panelLblNombre.setPreferredSize(new java.awt.Dimension(100, 43));
        panelLblNombre.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 10));

        lblNombre.setText("Nombre");
        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14));
        panelLblNombre.add(lblNombre);

        panelNombreCamp.add(panelLblNombre);

        panelCampoNombre.setMaximumSize(new java.awt.Dimension(350, 43));
        panelCampoNombre.setMinimumSize(new java.awt.Dimension(350, 43));
        panelCampoNombre.setPreferredSize(new java.awt.Dimension(350, 43));
        panelCampoNombre.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        campoNombreCampania.setFont(new java.awt.Font("Tahoma", 0, 12));
        campoNombreCampania.setMaximumSize(new java.awt.Dimension(200, 21));
        campoNombreCampania.setMinimumSize(new java.awt.Dimension(200, 21));
        campoNombreCampania.setPreferredSize(new java.awt.Dimension(200, 21));
        panelCampoNombre.add(campoNombreCampania);

        panelNombreCamp.add(panelCampoNombre);

        panelDatosNuevaCampania.add(panelNombreCamp);

        panelBarcoCamp.setMaximumSize(new java.awt.Dimension(450, 43));
        panelBarcoCamp.setMinimumSize(new java.awt.Dimension(450, 43));
        panelBarcoCamp.setPreferredSize(new java.awt.Dimension(450, 43));
        panelBarcoCamp.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        panelLbBarco.setMaximumSize(new java.awt.Dimension(100, 43));
        panelLbBarco.setMinimumSize(new java.awt.Dimension(100, 43));
        panelLbBarco.setPreferredSize(new java.awt.Dimension(100, 43));
        panelLbBarco.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 10));

        lblBarco.setText("Barco");
        lblBarco.setFont(new java.awt.Font("Tahoma", 0, 14));
        panelLbBarco.add(lblBarco);

        panelBarcoCamp.add(panelLbBarco);

        panelCampoBarco.setMaximumSize(new java.awt.Dimension(350, 43));
        panelCampoBarco.setMinimumSize(new java.awt.Dimension(350, 43));
        panelCampoBarco.setPreferredSize(new java.awt.Dimension(350, 43));
        panelCampoBarco.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        campoBarcoCampania.setFont(new java.awt.Font("Tahoma", 0, 12));
        campoBarcoCampania.setMaximumSize(new java.awt.Dimension(200, 21));
        campoBarcoCampania.setMinimumSize(new java.awt.Dimension(200, 21));
        campoBarcoCampania.setPreferredSize(new java.awt.Dimension(200, 21));
        panelCampoBarco.add(campoBarcoCampania);

        panelBarcoCamp.add(panelCampoBarco);

        panelDatosNuevaCampania.add(panelBarcoCamp);

        panelCapitanCamp.setMaximumSize(new java.awt.Dimension(450, 43));
        panelCapitanCamp.setMinimumSize(new java.awt.Dimension(450, 43));
        panelCapitanCamp.setPreferredSize(new java.awt.Dimension(450, 43));
        panelCapitanCamp.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        panelLblCapitan.setMaximumSize(new java.awt.Dimension(100, 43));
        panelLblCapitan.setMinimumSize(new java.awt.Dimension(100, 43));
        panelLblCapitan.setPreferredSize(new java.awt.Dimension(100, 43));
        panelLblCapitan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 10));

        lblCapitan.setText("Capitan");
        lblCapitan.setFont(new java.awt.Font("Tahoma", 0, 14));
        panelLblCapitan.add(lblCapitan);

        panelCapitanCamp.add(panelLblCapitan);

        panelCampoCapitan.setMaximumSize(new java.awt.Dimension(350, 43));
        panelCampoCapitan.setMinimumSize(new java.awt.Dimension(350, 43));
        panelCampoCapitan.setPreferredSize(new java.awt.Dimension(350, 43));
        panelCampoCapitan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        campoCapitanCampania.setFont(new java.awt.Font("Tahoma", 0, 12));
        campoCapitanCampania.setMaximumSize(new java.awt.Dimension(200, 21));
        campoCapitanCampania.setMinimumSize(new java.awt.Dimension(200, 21));
        campoCapitanCampania.setPreferredSize(new java.awt.Dimension(200, 21));
        panelCampoCapitan.add(campoCapitanCampania);

        panelCapitanCamp.add(panelCampoCapitan);

        panelDatosNuevaCampania.add(panelCapitanCamp);

        panelNuevaCampania.add(panelDatosNuevaCampania, java.awt.BorderLayout.CENTER);

        panelCentro.add(panelNuevaCampania);

        jScrollPane2.setViewportView(panelCentro);

        add(jScrollPane2, java.awt.BorderLayout.LINE_END);

        panelBtnCampania.setMaximumSize(new java.awt.Dimension(500, 50));
        panelBtnCampania.setMinimumSize(new java.awt.Dimension(500, 50));
        panelBtnCampania.setPreferredSize(new java.awt.Dimension(500, 50));
        panelBtnCampania.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        btnComenzarCampania.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnComenzarCampania.setText("Iniciar campaña");
        btnComenzarCampania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarCampaniaActionPerformed(evt);
            }
        });
        panelBtnCampania.add(btnComenzarCampania);

        btnPausarReanudarCampania.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnPausarReanudarCampania.setText("Pausar campaña");
        btnPausarReanudarCampania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausarReanudarCampaniaActionPerformed(evt);
            }
        });
        panelBtnCampania.add(btnPausarReanudarCampania);

        btnFinalizarCampania.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnFinalizarCampania.setText("Finalizar campaña");
        btnFinalizarCampania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCampaniaActionPerformed(evt);
            }
        });
        panelBtnCampania.add(btnFinalizarCampania);

        add(panelBtnCampania, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

private void btnComenzarCampaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarCampaniaActionPerformed
        boolean camposRequeridos = campoBarcoCampania.getText().length() > 2 && 
                campoCapitanCampania.getText().length() > 2  &&
                campoNombreCampania.getText().length() > 2;
        if (camposRequeridos) {  
            if (controllers.ControllerCampania.getInstance().nuevaCampania(campoNombreCampania.getText(), campoCapitanCampania.getText(), campoBarcoCampania.getText())){
                setGuiCampaniaIniciada();
            }
            else
              { JOptionPane.showMessageDialog(null, "Hubo un error al intentar guardar la nueva campaña"); }
        }
        else
        { JOptionPane.showMessageDialog(null,"Complete los campos de Nueva campaña con datos válidos"); }
}//GEN-LAST:event_btnComenzarCampaniaActionPerformed

private void btnPausarReanudarCampaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausarReanudarCampaniaActionPerformed
    if (!(getEstadoCampania()==2)){
        setGuiCampaniaPausada();
    }
    else
        { setGuiCampaniaReanudada(); }
    
}//GEN-LAST:event_btnPausarReanudarCampaniaActionPerformed

private void btnFinalizarCampaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCampaniaActionPerformed
        if (JOptionPane.showConfirmDialog(null,
                    "Atención! Está por finalizar la campaña en curso, está seguro?",
                    "Finalizar campaña", 
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
                    ) == 0) {
            setGuiCampaniaFinalizada();
        }
}//GEN-LAST:event_btnFinalizarCampaniaActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    agregaUnaFilaCampania(1,"nnombre","bbarcoo","ccapitan",2,new Date(2011, 4, 12),new Date(2011,5,4));
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    controllers.ControllerCampania.getInstance().obtenerCampanias();
}//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzarCampania;
    private javax.swing.JButton btnFinalizarCampania;
    private javax.swing.JButton btnPausarReanudarCampania;
    private javax.swing.JTextField campoBarcoCampania;
    private javax.swing.JTextField campoCapitanCampania;
    private javax.swing.JTextField campoNombreCampania;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXLabel lblBarco;
    private org.jdesktop.swingx.JXLabel lblCapitan;
    private org.jdesktop.swingx.JXLabel lblNombre;
    private org.jdesktop.swingx.JXLabel lblNuevaCampania;
    private org.jdesktop.swingx.JXLabel lblTituloCampanias;
    private org.jdesktop.swingx.JXLabel lblTituloTabla;
    private org.jdesktop.swingx.JXPanel panelBarcoCamp;
    private org.jdesktop.swingx.JXPanel panelBtnCampania;
    private org.jdesktop.swingx.JXPanel panelCampoBarco;
    private org.jdesktop.swingx.JXPanel panelCampoCapitan;
    private org.jdesktop.swingx.JXPanel panelCampoNombre;
    private org.jdesktop.swingx.JXPanel panelCapitanCamp;
    private org.jdesktop.swingx.JXPanel panelCentro;
    private org.jdesktop.swingx.JXPanel panelDatosNuevaCampania;
    private org.jdesktop.swingx.JXPanel panelLbBarco;
    private org.jdesktop.swingx.JXPanel panelLblCapitan;
    private org.jdesktop.swingx.JXPanel panelLblNombre;
    private org.jdesktop.swingx.JXPanel panelNombreCamp;
    private org.jdesktop.swingx.JXPanel panelNuevaCampania;
    private org.jdesktop.swingx.JXPanel panelTablaCampanias;
    private org.jdesktop.swingx.JXPanel panelTitulo;
    private org.jdesktop.swingx.JXPanel panelTituloNuevaCampania;
    private org.jdesktop.swingx.JXPanel panelTituloTabla;
    private org.jdesktop.swingx.JXTable tablaCampanias;
    // End of variables declaration//GEN-END:variables
    
    private void controlaPanelNuevaCampania(boolean estado){
        lblNuevaCampania.setEnabled(estado);
        lblNombre.setEnabled(estado);
        campoNombreCampania.setEnabled(estado);
        lblBarco.setEnabled(estado);
        campoBarcoCampania.setEnabled(estado);
        lblCapitan.setEnabled(estado);
        campoCapitanCampania.setEnabled(estado);        
    }

    public static PanelOpcCampanias getInstance() {
       if (unicaInstancia == null) {
          unicaInstancia = new PanelOpcCampanias();          
       }
       return unicaInstancia;
    }    
    
/* codigo de prueba para poder probar un panel simplemente haciendo "Run File" sobre su clase 
*/   
     public static void main(String[] args) {
        javax.swing.JFrame elFrame = new javax.swing.JFrame();
        JPanel elPanel= new PanelOpcCampanias();
        elFrame.setSize(500,500);
        elFrame.add(elPanel); 
        elFrame.setVisible(true);
    }


    public void setGuiCampaniaIniciada() {
        controlaPanelNuevaCampania(false);
        btnComenzarCampania.setVisible(false);
        btnFinalizarCampania.setVisible(true);
        btnPausarReanudarCampania.setVisible(true);
        setEstadoCampania(1);
        // controllers.ControllerCampania.getInstance().obtenerCampanias();
        
    }
    
    public void setGuiCampaniaPausada() {
        btnPausarReanudarCampania.setText("Reanudar campaña");
        setEstadoCampania(2);
        // controllers.ControllerCampania.getInstance().obtenerCampanias();
    }
    
    public void setGuiCampaniaReanudada() {
        btnPausarReanudarCampania.setText("Pausar campaña");        
        setEstadoCampania(1);
        // controllers.ControllerCampania.getInstance().obtenerCampanias();
    }
    
    public void setGuiCampaniaFinalizada() {
        controlaPanelNuevaCampania(true);
        campoBarcoCampania.setText("");
        campoCapitanCampania.setText("");
        campoNombreCampania.setText("");        
        btnPausarReanudarCampania.setVisible(false);
        btnFinalizarCampania.setVisible(false);
        btnComenzarCampania.setVisible(true);
        btnPausarReanudarCampania.setText("Pausar campaña");
        setEstadoCampania(0);
        // controllers.ControllerCampania.getInstance().obtenerCampanias();
    }

    /**
     * @return the colorOriginalBtnIniciar
     */
    public Color getColorOriginalBtnIniciar() {
        return colorOriginalBtnIniciar;
    }

    /**
     * @param colorOriginalBtnIniciar the colorOriginalBtnIniciar to set
     */
    public void setColorOriginalBtnIniciar(Color colorOriginalBtnIniciar) {
        this.colorOriginalBtnIniciar = colorOriginalBtnIniciar;
    }

    /**
     * @return the estadoCampania
     */
    public int getEstadoCampania() {
        return estadoCampania;
    }

    /**
     * @param estadoCampania the estadoCampania to set
     */
    public void setEstadoCampania(int estadoCampania) {
        this.estadoCampania = estadoCampania;
    }

    public void vaciaTabla() {                
        modeloTabla.setRowCount(0);
    }

    public void agregaUnaFilaCampania(int id, String nombre, String barco, String capitan, int estado, Date fechaInicio, Date fechaFin) {        
        Object[] fila = new Object[cantColumnas]; //creamos la fila
        PanelOpcCampaniasAcciones panelAcciones = new PanelOpcCampaniasAcciones();
        fila[NRO_COL_ACCIONES]=panelAcciones;
        fila[NRO_COL_FECHA_INI]=fechaInicio;
        fila[NRO_COL_FECHA_FIN]=fechaFin;
        fila[NRO_COL_CAPITAN]=capitan;
        fila[NRO_COL_NOMBRE_CAMP]=nombre;
        fila[NRO_COL_BARCO]=barco;
        fila[NRO_COL_ID_CAMP]=id;
        
        modeloTabla.addRow(fila);        
    }

    public void agregaUnaFilaCampania2() {        
        Object[] fila = new Object[2]; //creamos la fila
        fila[0]="Columna0"; //Fila0
        fila[1]="Columna1"; //Fila1
        modeloTabla.addRow(fila);        
    }
    
    private void inicializaTabla() {
        //String[] columnas = new String[cantColumnas];
        //columnas[NRO_COL_ID_CAMP]="ID";
        //columnas[NRO_COL_ACCIONES]="Acciones";
        //columnas[NRO_COL_BARCO]="Barco";
        //columnas[NRO_COL_CAPITAN]="Capitan";
        //columnas[NRO_COL_DURACION]="Duracion";
        //columnas[NRO_COL_FECHA_FIN]="Fecha Fin";
        //columnas[NRO_COL_FECHA_INI]="Fecha Inicio";
        //columnas[NRO_COL_NOMBRE_CAMP]="Nombre campaña";        
        //modeloTabla = new javax.swing.table.TableModel(new Object[][]{},columnas);        
        //tablaCampanias.setModel(modeloTabla);
                                       
                 //tablaCampanias.setDefaultRenderer(Object.class, new PanelOpcCampaniasAcciones());
         //tablaCampanias.setDefaultEditor(Object.class, new PanelOpcCampaniasAcciones());
        TableColumn columnaAcciones = new TableColumn();
        columnaAcciones.setHeaderValue("Acciones!");
        columnaAcciones.setMinWidth(100);
        columnaAcciones.setPreferredWidth(100);
        columnaAcciones.setCellEditor(new PanelOpcCampaniasAcciones());
        columnaAcciones.setCellRenderer(new PanelOpcCampaniasAcciones());        
        tablaCampanias.addColumn(columnaAcciones);        
        tablaCampanias.setEditingColumn(6);
        //tablaCampanias.setEditingRow(0);
        modeloTabla = (DefaultTableModel) tablaCampanias.getModel();
        tablaCampanias.setModel(modeloTabla);         
        
        
        
        vaciaTabla();
        // Se crea el JScrollPane, el JTable y se pone la cabecera...
         //JScrollPane scroll = new JScrollPane();
         //tablaCampanias.setDefaultRenderer(Object.class, new PanelOpcCampaniasAcciones());
         //tablaCampanias.setDefaultEditor(Object.class, new PanelOpcCampaniasAcciones());
         //scroll.setViewportView(tablaCampanias);
         //scroll.setColumnHeaderView (tablaCampanias.getTableHeader());        
        //tablaCampanias.setVisibleRowCount(6);
        
/* si queremos que algun campo sea editable, capturar el evento y demas... 
        TableColumn column = tablaCampanias.getColumnModel().getColumn(NRO_COL_ACCIONES);
        JXHyperlink btnGuardar = new JXHyperlink(); btnGuardar.setText("guardar");
        JXHyperlink btnModificar = new JXHyperlink(); btnModificar.setText("modif");
        JXHyperlink btnEliminar = new JXHyperlink(); btnEliminar.setText("Eliminar");
        
        
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlinkBtnGuardarActionPerformed(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //jXHyperlinkBtnModificarActionPerformed(evt);
                System.out.println("no hace nada xq falta codificar el método");
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //jXHyperlinkBtnEliminarActionPerformed(evt);
                System.out.println("no hace nada xq falta codificar el método");
            }
        });
        
        //Indicamos el CellEditor column
        column.setCellEditor(new DefaultCellEditor(btnEliminar));

        //Metodo para controlar el texto ingresado en el JTextField.

    }

    private void jXHyperlinkBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            //String tmp = this.fieldPago.getText();
            //Double Pago = Double.parseDouble(tmp);
            //Obtenemos el numero de fila donde estamos ubicamos en este momento.
            int fila = tablaCampanias.getSelectedRow();

            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "No se selecciono ninguna fila", "Mensaje", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int id = (int)tablaCampanias.getValueAt(fila, 0);
            Double Deuda = Double.parseDouble(tmp);
            tmp = String.valueOf(tablaCampanias.getValueAt(fila, 5));
            Double Saldo = Double.parseDouble(tmp);
            if (Pago < 0) {
                JOptionPane.showMessageDialog(this, "El pago no puede ser negativo", "Mensaje", JOptionPane.WARNING_MESSAGE);
                tablaCampanias.setValueAt(0.0, fila, 4);
                return;
            }

            //Actualizamos otra columna con los valores, esta columna debe ser editable
            tablaCampanias.setValueAt(Pago, fila, 5);
            tablaCampanias.repaint();
            modeloTabla.fireTableDataChanged();
            JOptionPane.showMessageDialog(this, "Presionaste Enter pago de " + Pago, "Mensaje", JOptionPane.WARNING_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
*/
    }   
    
}